
;CSMC 0.11u eflash
;IC6 technology file
;generated by GTE Version: 03.05.002  Build: @1650 (20130917032931) on Mar 13, 2019
;parameter file: /sto/stosh1/work/LIB/011_library/personal/zhouc/pdk_zhouc/011_eFlash/pdk_pcell/20190311/param/st11_techSelect_ic6_a8_8k.param
;AllProcess false
;metal4 false
;metal5 false
;metal6 false
;metal7 false
;metal8 true
;thickmetal4 false
;thickmetal5 false
;thickmetal6 false
;thickmetal7 false
;thickmetal8 false
;at_thickness_8k true
;at_thickness_12k false
;tt_thickness_25k false
;tt_thickness_35k false
;IC5 false
;IC6 true

controls(

 mfgGridResolution(
      ( 0.001000 )
 ) ;mfgGridResolution

) ;controls


layerDefinitions(

    techLayers(
;       ( LayerName       Layer#          Abbreviation     )
;       ( ---------       ------          ------------     )
        ( TB              1               TB               )
        ( TO              2               TO               )
        ( GT              3               GT               )
        ( SP              4               SP               )
        ( SN              5               SN               )
        ( W1              6               W1               )
        ( A1              7               A1               )
        ( W2              8               W2               )
        ( A2              9               A2               )
        ( CP              10              CP               )
        ( PT              11              PT               )
        ( IM              13              IM               )
        ( PC              14              PC               )
        ( NL              15              NL               )
        ( LR              16              LR               )
        ( HV              17              HV               )
        ( HN              18              HN               )
        ( HP              19              HP               )
        ( BN              20              BN               )
        ( NA              21              NA               )
        ( PA              22              PA               )
        ( RO              23              RO               )
        ( MP              24              MP               )
        ( SI              25              SI               )
        ( NG              26              NG               )
        ( NH              27              NH               )
        ( PH              28              PH               )
        ( LN              29              LN               )
        ( LP              30              LP               )
        ( PWB             31              PWB              )
        ( HR              33              HR               )
        ( PI              34              PI               )
        ( W3              40              W3               )
        ( A3              41              A3               )
        ( PD              44              PD               )
        ( MN              45              MN               )
        ( SE              46              SE               )
        ( SPW             53              SPW              )
        ( SNW             54              SNW              )
        ( DN              55              DN               )
        ( SCRIBE          60              SCRIBE           )
        ( W4              61              W4               )
        ( A4              62              A4               )
        ( DP              63              DP               )
        ( NM              70              NM               )
        ( HF              73              HF               )
        ( NX              76              NX               )
        ( PX              77              PX               )
        ( MCT             78              MCT              )
        ( FUSE            81              FUSE             )
        ( TAP             83              TAP              )
        ( TT              86              TT               )
        ( PB              89              PB               )
        ( W5              91              W5               )
        ( A5              92              A5               )
        ( WT              93              WT               )
        ( AT              94              AT               )
        ( W6              95              W6               )
        ( A6              96              A6               )
        ( W7              97              W7               )
        ( A7              98              A7               )
        ( SEALRING        100             SEALRING         )
        ( LMARK           101             LMARK            )
        ( PMDMY           102             PMDMY            )
        ( LOGO            103             LOGO             )
        ( VARMOS          105             VARMOS           )
        ( RES_HR1K        107             RES_HR1K         )
        ( RES_HR2K        108             RES_HR2K         )
        ( RES_FUSE        109             RES_FUSE         )
        ( DCTY            110             DCTY             )
        ( EXT_SUB         111             EXT_SUB          )
        ( RES_NW          112             RES_NW           )
        ( DIODE           113             DIODE            )
        ( CAP             114             CAP              )
        ( BJT             115             BJT              )
        ( RFDUM           116             RFDUM            )
        ( INDUM           117             INDUM            )
        ( EXCL            118             EXCL             )
        ( RES_M6          119             RES_M6           )
        ( RES_M7          120             RES_M7           )
        ( A1TEXT          121             A1TEXT           )
        ( A2TEXT          122             A2TEXT           )
        ( A3TEXT          123             A3TEXT           )
        ( A4TEXT          124             A4TEXT           )
        ( A5TEXT          125             A5TEXT           )
        ( ATTEXT          126             ATTEXT           )
        ( A6TEXT          127             A6TEXT           )
        ( A7TEXT          128             A7TEXT           )
        ( TTSLOT          130             TTSLOT           )
        ( A7SLOT          131             A7SLOT           )
        ( A6SLOT          132             A6SLOT           )
        ( ATSLOT          133             ATSLOT           )
        ( A5SLOT          134             A5SLOT           )
        ( A4SLOT          135             A4SLOT           )
        ( A1SLOT          136             A1SLOT           )
        ( A2SLOT          137             A2SLOT           )
        ( A3SLOT          138             A3SLOT           )
        ( IPB             147             IPB              )
        ( TODUM           148             TODUM            )
        ( GTDUM           149             GTDUM            )
        ( PSUB2           150             PSUB2            )
        ( MCTM7           151             MCTM7            )
        ( MCTM6           152             MCTM6            )
        ( MCTM5           153             MCTM5            )
        ( MCTM4           154             MCTM4            )
        ( RNDMY           155             RNDMY            )
        ( RPDMY           156             RPDMY            )
        ( DUMBM           157             DUMBM            )
        ( DUMBP           158             DUMBP            )
        ( DUMBA           159             DUMBA            )
        ( NODMF           160             NODMF            )
        ( RES_TO          161             RES_TO           )
        ( RES_PY          162             RES_PY           )
        ( RES_M1          163             RES_M1           )
        ( RES_M2          164             RES_M2           )
        ( RES_M3          165             RES_M3           )
        ( RES_M4          166             RES_M4           )
        ( RES_M5          167             RES_M5           )
        ( RES_MT          168             RES_MT           )
        ( RES_HR          169             RES_HR           )
        ( A1DUM           170             A1DUM            )
        ( A2DUM           171             A2DUM            )
        ( A3DUM           172             A3DUM            )
        ( A4DUM           173             A4DUM            )
        ( A5DUM           174             A5DUM            )
        ( ATDUM           175             ATDUM            )
        ( TTDUM           176             TTDUM            )
        ( A6DUM           177             A6DUM            )
        ( A7DUM           178             A7DUM            )
        ( VARJUN          179             VARJUN           )
        ( ESD             180             ESD              )
        ( OPCBLK          181             OPCBLK           )
        ( VTSRAM          182             VTSRAM           )
        ( MCTM3           183             MCTM3            )
        ( EECELL          184             EECELL           )
        ( HFT             185             HFT              )
        ( MOM             186             MOM              )
        ( IPTAG           187             IPTAG            )
        ( UHVM            188             UHVM             )
        ( MergeRing       189             MergeRing        )
    ) ;techLayers

    techPurposes(
;       ( PurposeName     Purpose#        Abbreviation     )
;       ( ---------       ------          ------------     )
        ( mark            1               mark             )
        ( dumy            2               dumy             )
        ( g2              6               g2               )
        ( g3              7               g3               )
        ( ter             8               ter              )
        ( iso             9               iso              )
        ( m2              15              m2               )
        ( txt             20              txt              )
        ( DB              30              DB               )
        ( tag             63              tag              )
    ) ;techPurposes

    techDerivedLayers(
;       ( DerivedName     Layer#          ( Composition )                  )
;       ( -----------     ------          ---------------                  )
        ( sn_ovlp_sp      1000            ( SN 'and SP )                   )
        ( techfile21596   1001            ( GT 'and W1 )                   )
        ( w1_err          1002            ( TO 'and techfile21596 )        )
        ( w1_to           1003            ( TO 'and W1 )                   )
    ) ;techDerivedLayers

    techLayerPurposePriorities(
;       ( LayerName       Purpose          )
;       ( ---------       -------          )
        ( TB              drawing          )
        ( TO              drawing          )
        ( GT              drawing          )
        ( SP              drawing          )
        ( SN              drawing          )
        ( SPW             drawing          )
        ( SNW             drawing          )
        ( W1              drawing          )
        ( A1              drawing          )
        ( W2              drawing          )
        ( A2              drawing          )
        ( W3              drawing          )
        ( A3              drawing          )
        ( W4              drawing          )
        ( A4              drawing          )
        ( W5              drawing          )
        ( A5              drawing          )
        ( W6              drawing          )
        ( A6              drawing          )
        ( W7              drawing          )
        ( WT              drawing          )
        ( A7              drawing          )
        ( AT              drawing          )
        ( TT              drawing          )
        ( CP              drawing          )
        ( PT              drawing          )
        ( IM              drawing          )
        ( PC              drawing          )
        ( NL              drawing          )
        ( LR              drawing          )
        ( HV              drawing          )
        ( HN              drawing          )
        ( HP              drawing          )
        ( BN              drawing          )
        ( NA              drawing          )
        ( PA              drawing          )
        ( SE              drawing          )
        ( SI              drawing          )
        ( RO              drawing          )
        ( NH              drawing          )
        ( PH              drawing          )
        ( NG              drawing          )
        ( LN              drawing          )
        ( LP              drawing          )
        ( PWB             drawing          )
        ( MN              drawing          )
        ( MP              drawing          )
        ( PD              drawing          )
        ( DN              drawing          )
        ( HR              drawing          )
        ( PI              drawing          )
        ( TAP             drawing          )
        ( DP              drawing          )
        ( NM              drawing          )
        ( HF              drawing          )
        ( NX              drawing          )
        ( PX              drawing          )
        ( MCT             drawing          )
        ( SCRIBE          drawing          )
        ( FUSE            drawing          )
        ( PB              drawing          )
        ( A1TEXT          drawing          )
        ( A2TEXT          drawing          )
        ( A3TEXT          drawing          )
        ( A4TEXT          drawing          )
        ( A5TEXT          drawing          )
        ( A6TEXT          drawing          )
        ( A7TEXT          drawing          )
        ( ATTEXT          drawing          )
        ( UHVM            mark             )
        ( MergeRing       mark             )
        ( SEALRING        mark             )
        ( LMARK           mark             )
        ( PMDMY           mark             )
        ( LOGO            mark             )
        ( PSUB2           mark             )
        ( MCTM7           mark             )
        ( MCTM6           mark             )
        ( MCTM5           mark             )
        ( MCTM4           mark             )
        ( MCTM3           mark             )
        ( VARMOS          mark             )
        ( ESD             mark             )
        ( DCTY            mark             )
        ( RES_TO          mark             )
        ( RES_PY          mark             )
        ( RES_M1          mark             )
        ( RES_M2          mark             )
        ( RES_M3          mark             )
        ( RES_M4          mark             )
        ( RES_M5          mark             )
        ( RES_M6          mark             )
        ( RES_M7          mark             )
        ( RES_MT          mark             )
        ( RES_HR1K        mark             )
        ( RES_HR2K        mark             )
        ( RES_FUSE        mark             )
        ( EXT_SUB         mark             )
        ( RES_NW          mark             )
        ( RES_HR          mark             )
        ( HFT             mark             )
        ( RNDMY           mark             )
        ( RPDMY           mark             )
        ( DIODE           mark             )
        ( DIODE           iso              )
        ( MCT             mark             )
        ( DN              mark             )
        ( EECELL          mark             )
        ( IPTAG           tag              )
        ( MOM             mark             )
        ( MOM             ter              )
        ( CAP             mark             )
        ( BJT             mark             )
        ( RFDUM           mark             )
        ( INDUM           mark             )
        ( RFDUM           g2               )
        ( EXCL            mark             )
        ( DUMBM           mark             )
        ( DUMBP           mark             )
        ( DUMBA           mark             )
        ( NODMF           mark             )
        ( OPCBLK          mark             )
        ( VTSRAM          mark             )
        ( VARJUN          mark             )
        ( IPB             mark             )
        ( A1SLOT          slot             )
        ( A2SLOT          slot             )
        ( A3SLOT          slot             )
        ( TB              txt              )
        ( A4SLOT          slot             )
        ( PT              txt              )
        ( A5SLOT          slot             )
        ( A6SLOT          slot             )
        ( A7SLOT          slot             )
        ( ATSLOT          slot             )
        ( TTSLOT          slot             )
        ( A1DUM           DB               )
        ( A1DUM           dumy             )
        ( A2DUM           DB               )
        ( A3DUM           DB               )
        ( A4DUM           DB               )
        ( A5DUM           DB               )
        ( A6DUM           DB               )
        ( A7DUM           DB               )
        ( ATDUM           DB               )
        ( TTDUM           DB               )
        ( A2DUM           dumy             )
        ( A3DUM           dumy             )
        ( A4DUM           dumy             )
        ( A5DUM           dumy             )
        ( A6DUM           dumy             )
        ( A7DUM           dumy             )
        ( ATDUM           dumy             )
        ( TTDUM           dumy             )
        ( TODUM           dumy             )
        ( GTDUM           dumy             )
        ( A1              pin              )
        ( A2              pin              )
        ( A3              pin              )
        ( A4              pin              )
        ( A5              pin              )
        ( A6              pin              )
        ( A7              pin              )
        ( AT              pin              )
        ( TT              pin              )
        ( A1              net              )
        ( A2              net              )
        ( A3              net              )
        ( A4              net              )
        ( A5              net              )
        ( A6              net              )
        ( A7              net              )
        ( AT              net              )
        ( TT              net              )
        ( A1              boundary         )
        ( A2              boundary         )
        ( A3              boundary         )
        ( A4              boundary         )
        ( A5              boundary         )
        ( A6              boundary         )
        ( A7              boundary         )
        ( AT              boundary         )
        ( TT              boundary         )
    ) ;techLayerPurposePriorities

    techDisplays(
;       ( LayerName       Purpose         Packet                          Vis Sel Chg Drg Valid )
;       ( ---------       -------         ------                          --- --- --- --- ----- )
        ( TB              drawing         TB                              t   t   t   t   t     )
        ( TO              drawing         TO                              t   t   t   t   t     )
        ( GT              drawing         GT                              t   t   t   t   t     )
        ( SP              drawing         SP                              t   t   t   t   t     )
        ( SN              drawing         SN                              t   t   t   t   t     )
        ( SPW             drawing         SPW                             t   t   t   t   t     )
        ( SNW             drawing         SNW                             t   t   t   t   t     )
        ( W1              drawing         aabs_vP1drawing                 t   t   t   t   t     )
        ( A1              drawing         aabs_m1drawing                  t   t   t   t   t     )
        ( W2              drawing         aabs_v12drawing                 t   t   t   t   t     )
        ( A2              drawing         aabs_m2drawing                  t   t   t   t   t     )
        ( W3              drawing         aabs_v23drawing                 t   t   t   t   t     )
        ( A3              drawing         aabs_m3drawing                  t   t   t   t   t     )
        ( W4              drawing         aabs_v34drawing                 t   t   t   t   t     )
        ( A4              drawing         aabs_m4drawing                  t   t   t   t   t     )
        ( W5              drawing         aabs_v45drawing                 t   t   t   t   t     )
        ( A5              drawing         aabs_m5drawing                  t   t   t   t   t     )
        ( W6              drawing         aabs_v56drawing                 t   t   t   t   t     )
        ( A6              drawing         aabs_m6drawing                  t   t   t   t   t     )
        ( W7              drawing         aabs_v67drawing                 t   t   t   t   t     )
        ( WT              drawing         aabs_v78drawing                 t   t   t   t   t     )
        ( A7              drawing         aabs_m7drawing                  t   t   t   t   t     )
        ( AT              drawing         aabs_m8drawing                  t   t   t   t   t     )
        ( TT              drawing         aabs_m9drawing                  t   t   t   t   t     )
        ( CP              drawing         CP                              t   t   t   t   t     )
        ( PT              drawing         PT                              t   t   t   t   t     )
        ( IM              drawing         IM                              t   t   t   t   t     )
        ( PC              drawing         PC                              t   t   t   t   t     )
        ( NL              drawing         NL                              t   t   t   t   t     )
        ( LR              drawing         LR                              t   t   t   t   t     )
        ( HV              drawing         HV                              t   t   t   t   t     )
        ( HN              drawing         HN                              t   t   t   t   t     )
        ( HP              drawing         HP                              t   t   t   t   t     )
        ( BN              drawing         BN                              t   t   t   t   t     )
        ( NA              drawing         annotate                        t   t   t   t   t     )
        ( PA              drawing         annotate1                       t   t   t   t   t     )
        ( SE              drawing         SE                              t   t   t   t   t     )
        ( SI              drawing         SAB                             t   t   t   t   t     )
        ( RO              drawing         RO                              t   t   t   t   t     )
        ( NH              drawing         annotate3                       t   t   t   t   t     )
        ( PH              drawing         annotate4                       t   t   t   t   t     )
        ( NG              drawing         NG                              t   t   t   t   t     )
        ( LN              drawing         LN                              t   t   t   t   t     )
        ( LP              drawing         annotate2                       t   t   t   t   t     )
        ( PWB             drawing         PWB                             t   t   t   t   t     )
        ( MN              drawing         annotate6                       t   t   t   t   t     )
        ( MP              drawing         annotate7                       t   t   t   t   t     )
        ( PD              drawing         PD                              t   t   t   t   t     )
        ( DN              drawing         DN                              t   t   t   t   t     )
        ( HR              drawing         annotate8                       t   t   t   t   t     )
        ( PI              drawing         annotate9                       t   t   t   t   t     )
        ( TAP             drawing         TAP                             t   t   t   t   t     )
        ( DP              drawing         DP                              t   t   t   t   t     )
        ( NM              drawing         NM                              t   t   t   t   t     )
        ( HF              drawing         HF                              t   t   t   t   t     )
        ( NX              drawing         NX                              t   t   t   t   t     )
        ( PX              drawing         PX                              t   t   t   t   t     )
        ( MCT             drawing         annotate10                      t   t   t   t   t     )
        ( SCRIBE          drawing         SCRIBE                          t   t   t   t   t     )
        ( FUSE            drawing         FUSE                            t   t   t   t   t     )
        ( PB              drawing         PB                              t   t   t   t   t     )
        ( A1TEXT          drawing         A1TEXT                          t   t   t   t   t     )
        ( A2TEXT          drawing         A2TEXT                          t   t   t   t   t     )
        ( A3TEXT          drawing         A3TEXT                          t   t   t   t   t     )
        ( A4TEXT          drawing         A4TEXT                          t   t   t   t   t     )
        ( A5TEXT          drawing         A5TEXT                          t   t   t   t   t     )
        ( A6TEXT          drawing         A6TEXT                          t   t   t   t   t     )
        ( A7TEXT          drawing         A7TEXT                          t   t   t   t   t     )
        ( ATTEXT          drawing         ATTEXT                          t   t   t   t   t     )
        ( UHVM            mark            UHVM                            t   t   t   t   t     )
        ( MergeRing       mark            MergeRing                       t   t   t   t   t     )
        ( SEALRING        mark            Unrouted1                       t   t   t   t   t     )
        ( LMARK           mark            Unrouted2                       t   t   t   t   t     )
        ( PMDMY           mark            Unrouted3                       t   t   t   t   t     )
        ( LOGO            mark            Unrouted4                       t   t   t   t   t     )
        ( PSUB2           mark            Unrouted5                       t   t   t   t   t     )
        ( MCTM7           mark            Unrouted6                       t   t   t   t   t     )
        ( MCTM6           mark            Unrouted6                       t   t   t   t   t     )
        ( MCTM5           mark            Unrouted6                       t   t   t   t   t     )
        ( MCTM4           mark            Unrouted66                      t   t   t   t   t     )
        ( MCTM3           mark            Unrouted67                      t   t   t   t   t     )
        ( VARMOS          mark            Unrouted7                       t   t   t   t   t     )
        ( ESD             mark            annotate11                      t   t   t   t   t     )
        ( DCTY            mark            DCTY                            t   t   t   t   t     )
        ( RES_TO          mark            RES_TO                          t   t   t   t   t     )
        ( RES_PY          mark            RES_POLY                        t   t   t   t   t     )
        ( RES_M1          mark            Unrouted8                       t   t   t   t   t     )
        ( RES_M2          mark            Unrouted8                       t   t   t   t   t     )
        ( RES_M3          mark            Unrouted8                       t   t   t   t   t     )
        ( RES_M4          mark            Unrouted8                       t   t   t   t   t     )
        ( RES_M5          mark            Unrouted8                       t   t   t   t   t     )
        ( RES_M6          mark            Unrouted8                       t   t   t   t   t     )
        ( RES_M7          mark            Unrouted8                       t   t   t   t   t     )
        ( RES_MT          mark            Unrouted8                       t   t   t   t   t     )
        ( RES_HR1K        mark            Unrouted8                       t   t   t   t   t     )
        ( RES_HR2K        mark            Unrouted8                       t   t   t   t   t     )
        ( RES_FUSE        mark            Unrouted8                       t   t   t   t   t     )
        ( EXT_SUB         mark            Unrouted8                       t   t   t   t   t     )
        ( RES_NW          mark            Unrouted8                       t   t   t   t   t     )
        ( RES_HR          mark            Unrouted8                       t   t   t   t   t     )
        ( HFT             mark            HFT                             t   t   t   t   t     )
        ( RNDMY           mark            Unrouted9                       t   t   t   t   t     )
        ( RPDMY           mark            Unrouted                        t   t   t   t   t     )
        ( DIODE           mark            DIODE                           t   t   t   t   t     )
        ( DIODE           iso             DIODE_iso                       t   t   t   t   t     )
        ( MCT             mark            MCT_mark                        t   t   t   t   t     )
        ( DN              mark            DN_mark                         t   t   t   t   t     )
        ( EECELL          mark            EECELL                          t   t   t   t   t     )
        ( IPTAG           tag             IPTAG_tag                       t   t   t   t   t     )
        ( MOM             mark            MOM_mark                        t   t   t   t   t     )
        ( MOM             ter             MOM_ter                         t   t   t   t   t     )
        ( CAP             mark            CAP                             t   t   t   t   t     )
        ( BJT             mark            BJT                             t   t   t   t   t     )
        ( RFDUM           mark            designFlow1                     t   t   t   t   t     )
        ( INDUM           mark            designFlow2                     t   t   t   t   t     )
        ( RFDUM           g2              RFDUM_g2                        t   t   t   t   t     )
        ( EXCL            mark            EXCL                            t   t   t   t   t     )
        ( DUMBM           mark            designFlow3                     t   t   t   t   t     )
        ( DUMBP           mark            designFlow4                     t   t   t   t   t     )
        ( DUMBA           mark            designFlow5                     t   t   t   t   t     )
        ( NODMF           mark            NODMF                           t   t   t   t   t     )
        ( OPCBLK          mark            designFlow7                     t   t   t   t   t     )
        ( VTSRAM          mark            designFlow8                     t   t   t   t   t     )
        ( VARJUN          mark            designFlow9                     t   t   t   t   t     )
        ( IPB             mark            ipb                             t   t   t   t   t     )
        ( A1SLOT          slot            A1SLOT                          t   t   t   t   t     )
        ( A2SLOT          slot            A2SLOT                          t   t   t   t   t     )
        ( A3SLOT          slot            A3SLOT                          t   t   t   t   t     )
        ( TB              txt             TB_txt                          t   t   t   t   t     )
        ( A4SLOT          slot            A4SLOT                          t   t   t   t   t     )
        ( PT              txt             PT_txt                          t   t   t   t   t     )
        ( A5SLOT          slot            A5SLOT                          t   t   t   t   t     )
        ( A6SLOT          slot            A6SLOT                          t   t   t   t   t     )
        ( A7SLOT          slot            A7SLOT                          t   t   t   t   t     )
        ( ATSLOT          slot            ATSLOT                          t   t   t   t   t     )
        ( TTSLOT          slot            TTSLOT                          t   t   t   t   t     )
        ( A1DUM           DB              A1DUM_DB                        t   t   t   t   nil   )
        ( A1DUM           dumy            A1DUM                           t   t   t   t   t     )
        ( A2DUM           DB              A2DUM_DB                        t   t   t   t   nil   )
        ( A3DUM           DB              A3DUM_DB                        t   t   t   t   nil   )
        ( A4DUM           DB              A4DUM_DB                        t   t   t   t   nil   )
        ( A5DUM           DB              A5DUM_DB                        t   t   t   t   nil   )
        ( A6DUM           DB              A6DUM_DB                        t   t   t   t   nil   )
        ( A7DUM           DB              A7DUM_DB                        t   t   t   t   nil   )
        ( ATDUM           DB              ATDUM_DB                        t   t   t   t   nil   )
        ( TTDUM           DB              TTDUM_DB                        t   t   t   t   nil   )
        ( A2DUM           dumy            A2DUM                           t   t   t   t   t     )
        ( A3DUM           dumy            A3DUM                           t   t   t   t   t     )
        ( A4DUM           dumy            A4DUM                           t   t   t   t   t     )
        ( A5DUM           dumy            A5DUM                           t   t   t   t   t     )
        ( A6DUM           dumy            A6DUM                           t   t   t   t   t     )
        ( A7DUM           dumy            A7DUM                           t   t   t   t   t     )
        ( ATDUM           dumy            ATDUM                           t   t   t   t   t     )
        ( TTDUM           dumy            TTDUM                           t   t   t   t   t     )
        ( TODUM           dumy            TODUM                           t   t   t   t   t     )
        ( GTDUM           dumy            GTDUM                           t   t   t   t   t     )
        ( A1              pin             aabs_m1pin                      t   t   t   t   t     )
        ( A2              pin             aabs_m2pin                      t   t   t   t   t     )
        ( A3              pin             aabs_m3pin                      t   t   t   t   t     )
        ( A4              pin             aabs_m4pin                      t   t   t   t   t     )
        ( A5              pin             aabs_m5pin                      t   t   t   t   t     )
        ( A6              pin             aabs_m6pin                      t   t   t   t   t     )
        ( A7              pin             aabs_m7pin                      t   t   t   t   t     )
        ( AT              pin             aabs_m8pin                      t   t   t   t   t     )
        ( TT              pin             aabs_m8pin                      t   t   t   t   t     )
        ( A1              net             aabs_m1net                      t   t   t   t   t     )
        ( A2              net             aabs_m2net                      t   t   t   t   t     )
        ( A3              net             aabs_m3net                      t   t   t   t   t     )
        ( A4              net             aabs_m4net                      t   t   t   t   t     )
        ( A5              net             aabs_m5net                      t   t   t   t   t     )
        ( A6              net             aabs_m6net                      t   t   t   t   t     )
        ( A7              net             aabs_m7net                      t   t   t   t   t     )
        ( AT              net             aabs_m8net                      t   t   t   t   t     )
        ( TT              net             aabs_m8net                      t   t   t   t   t     )
        ( A1              boundary        aabs_m1boundary                 t   t   t   t   t     )
        ( A2              boundary        aabs_m2boundary                 t   t   t   t   t     )
        ( A3              boundary        aabs_m3boundary                 t   t   t   t   t     )
        ( A4              boundary        aabs_m4boundary                 t   t   t   t   t     )
        ( A5              boundary        aabs_m5boundary                 t   t   t   t   t     )
        ( A6              boundary        aabs_m6boundary                 t   t   t   t   t     )
        ( A7              boundary        aabs_m7boundary                 t   t   t   t   t     )
        ( AT              boundary        aabs_m8boundary                 t   t   t   t   t     )
        ( TT              boundary        aabs_m8boundary                 t   t   t   t   t     )
    ) ;techDisplays

    techLayerPurposePriorities(
;       ( LayerName       Purpose          )
;       ( ---------       -------          )
    
        ( text                 drawing          )
        ( prBoundary      drawing          )
      
    ) ;techLayerPurposePriorities
    techDisplays(
;       ( LayerName       Purpose         Packet                          Vis Sel Chg Drg Valid )
;       ( ---------       -------         ------                          --- --- --- --- ----- )
        ( text                 drawing         text                                           t   t   t   t   t     )
        ( prBoundary      drawing         aabs_prBoundarydrawing          t   t   t   t   t     )
       
    ) ;techDisplays
    techDerivedLayers(
;       ( DerivedName     Layer#          ( Composition )                  )
;       ( -----------     ------          ---------------                  )
        ( sn_ovlp_sp      1000            ( SN 'and SP )                   )
        ( techfile21596   1001            ( GT 'and W1 )                   )
        ( w1_err          1002            ( TO 'and techfile21596 )        )
        ( w1_to           1003            ( TO 'and W1 )                   )
    ) ;techDerivedLayers
 

) ;layerDefinitions


layerRules(

    functions(
;       ( layer           function        maskNumber       )
;       ( -----           --------        ----------       )
        ( TB              "nwell"         1                )
        ( TO              "diff"          2                )
        ( SN              "nplus"         3                )
        ( SP              "pplus"         4                )
        ( GT              "poly"          5                )
        ( W1              "cut"           6                )
        ( A1              "metal"         7                )
        ( W2              "cut"           8                )
        ( A2              "metal"         9                )
        ( W3              "cut"           10               )
        ( A3              "metal"         11               )
        ( W4              "cut"           12               )
        ( A4              "metal"         13               )
        ( W5              "cut"           14               )
        ( A5              "metal"         15               )
        ( W6              "cut"           16               )
        ( A6              "metal"         17               )
        ( W7              "cut"           18               )
        ( A7              "metal"         19               )
        ( WT              "cut"           20               )
        ( AT              "metal"         21               )
    ) ;functions

    routingDirections(
;       ( layer           direction        )
;       ( -----           ---------        )
        ( A1              "horizontal"     )
        ( A2              "vertical"       )
        ( A3              "horizontal"     )
        ( A4              "vertical"       )
        ( A5              "horizontal"     )
        ( A6              "vertical"       )
        ( A7              "horizontal"     )
        ( AT              "vertical"       )
    ) ;routingDirections

) ;layerRules


viaDefs(

    standardViaDefs(
;       ( viaDefName      layer1      layer2      ( cutLayer    cutWidth    cutHeight   [resPerCut]  )
;           ( cutRows cutCols (cutSpace)       )
;           (layer1Enc)     (layer2Enc)     (layer1Offset)  (layer2Offset)  (origOffset)    
;         [ implant1    (implantEnc1)     [ implant2    (implantEnc2)     [ well/substrate  ]]]
;       )
;       ( ------------------------------------------------------------------------------------------ )
        ( NDIFF_M1        TO          A1          ( W1          0.14        0.14                     )
            ( 1       1       (0.18 0.18)      )
            (0.06 0.06)     (0.0 0.045)     (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
            SN          (0.16 0.16)     
        )

        ( PDIFF_M1        TO          A1          ( W1          0.14        0.14                     )
            ( 1       1       (0.18 0.18)      )
            (0.06 0.06)     (0.0 0.045)     (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
            SP          (0.16 0.16)     
        )

        ( POLY_M1         GT          A1          ( W1          0.14        0.14                     )
            ( 1       1       (0.18 0.18)      )
            (0.06 0.06)     (0.0 0.045)     (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
        )

        ( M1_M2           A1          A2          ( W2          0.17        0.17                     )
            ( 1       1       (0.26 0.26)      )
            (0.005 0.045)   (0.005 0.045)   (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
        )

        ( M2_M3           A2          A3          ( W3          0.17        0.17                     )
            ( 1       1       (0.26 0.26)      )
            (0.005 0.045)   (0.005 0.045)   (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
        )

        ( M3_M4           A3          A4          ( W4          0.17        0.17                     )
            ( 1       1       (0.26 0.26)      )
            (0.005 0.045)   (0.005 0.045)   (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
        )

        ( M4_M5           A4          A5          ( W5          0.17        0.17                     )
            ( 1       1       (0.26 0.26)      )
            (0.005 0.045)   (0.005 0.045)   (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
        )

        ( M5_M6           A5          A6          ( W6          0.17        0.17                     )
            ( 1       1       (0.26 0.26)      )
            (0.005 0.045)   (0.005 0.045)   (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
        )

        ( M6_M7           A6          A7          ( W7          0.17        0.17                     )
            ( 1       1       (0.26 0.26)      )
            (0.005 0.045)   (0.005 0.045)   (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
        )

        ( M7_MT           A7          AT          ( WT          0.32        0.32                     )
            ( 1       1       (0.485 0.485)    )
            (0.005 0.045)   (0.02 0.11)     (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
        )

    ) ;standardViaDefs

    customViaDefs(
;       ( viaDefName      libName     cellName    viewName    botLayer    topLayer    resPerCut    )
;       ( ----------      -------     --------    --------    --------    --------    ---------    )
        ( M1_M2_via       n1128       M1_M2       via         A1          A2          8            )
        ( M2_M3_via       n1128       M2_M3       via         A2          A3          8            )
        ( M3_M4_via       n1128       M3_M4       via         A3          A4          8            )
        ( M4_M5_via       n1128       M4_M5       via         A4          A5          8            )
        ( M5_M6_via       n1128       M5_M6       via         A5          A6          8            )
        ( M6_M7_via       n1128       M6_M7       via         A6          A7          8            )
        ( M7_MT_via       n1128       M7_MT       via         A7          AT          5            )
    ) ;customViaDefs

) ;viaDefs


constraintGroups(
;   ( group           override
;     -----           --------

    ( "foundry"

        spacings(
;           ( constraint                      layer1          layer2          value            )
;           ( ----------                      ------          ------          -----            )
            (minWidth                        TO                              0.135           
                'ref "TO.a")
            (minWidth                        GT                              0.13            
                'ref "GT.a")
            (minWidth                        A1                              0.14            
                'ref "A1.a")
            (minSpacing                      TO                              0.185           
                'ref "TO.c")
            (minSpacing                      GT                              0.145           
                'ref "GT.d")
            (minArea                         A1                              0.1             
                'ref "A1.h")
            (minArea                         TO                              0.1             
                'ref "TO.n")
            (minArea                         GT                              0.073           
                'ref "GT.j")
            (minHoleArea                     A1                              0.162           
                'ref "A1.i")
            (minHoleArea                     TO                              0.122           
                'ref "TO.o")
            (minHoleArea                     GT                              0.122           
                'ref "GT.k")
            (minWidth                        A2                              0.18            
                'ref "An.a")
            (minArea                         A2                              0.117           
                'ref "An.h")
            (minHoleArea                     A2                              0.215           
                'ref "An.i")
            (minWidth                        A3                              0.18            
                'ref "An.a")
            (minArea                         A3                              0.117           
                'ref "An.h")
            (minHoleArea                     A3                              0.215           
                'ref "An.i")
            (minWidth                        A4                              0.18            
                'ref "An.a")
            (minArea                         A4                              0.117           
                'ref "An.h")
            (minHoleArea                     A4                              0.215           
                'ref "An.i")
            (minWidth                        A5                              0.18            
                'ref "An.a")
            (minArea                         A5                              0.117           
                'ref "An.h")
            (minHoleArea                     A5                              0.215           
                'ref "An.i")
            (minWidth                        A6                              0.18            
                'ref "An.a")
            (minArea                         A6                              0.117           
                'ref "An.h")
            (minHoleArea                     A6                              0.215           
                'ref "An.i")
            (minWidth                        A7                              0.18            
                'ref "An.a")
            (minArea                         A7                              0.117           
                'ref "An.h")
            (minHoleArea                     A7                              0.215           
                'ref "An.i")
            (minWidth                        AT                              0.4             
                'ref "AT.a")
            (minArea                         AT                              0.562           
                'ref "AT.e")
            (minHoleArea                     AT                              0.565           
                'ref "AT.f")
            (minSpacing                      W1                              0.165           
                'ref "W1.b")
            (minSpacing                      W2                              0.195           
                'ref "Wn.b")
            (minSpacing                      W3                              0.195           
                'ref "Wn.b")
            (minSpacing                      W4                              0.195           
                'ref "Wn.b")
            (minSpacing                      W5                              0.195           
                'ref "Wn.b")
            (minSpacing                      W6                              0.195           
                'ref "Wn.b")
            (minSpacing                      W7                              0.195           
                'ref "Wn.b")
            (minSpacing                      WT                              0.315           
                'ref "WT.b")
        ) ;spacings

        orderedSpacings(
;           ( constraint                      layer1          layer2          [layer3]        value            )
;           ( ----------                      ------          ------          --------        -----            )
            (minOppExtension                 TO              W1                              ( 0.06 0.06 )   
                'ref "W1.e")
            (minOppExtension                 GT              W1                              ( 0.06 0.06 )   
                'ref "W1.f")
            (minOppExtension                 SN              w1_to                           ( 0.08 0.08 )   
                'ref "W1.g")
            (minOppExtension                 SP              w1_to                           ( 0.08 0.08 )   
                'ref "W1.h")
            (minOppExtension                 A1              W1                              (0.0 0.045)     
                'ref "A1.c")
            (minOppExtension                 A1              W2                              (0.005 0.045)   
                'ref "Wn.c")
            (minOppExtension                 A2              W3                              (0.005 0.045)   
                'ref "Wn.c")
            (minOppExtension                 A3              W4                              (0.005 0.045)   
                'ref "Wn.c")
            (minOppExtension                 A4              W5                              (0.005 0.045)   
                'ref "Wn.c")
            (minOppExtension                 A5              W6                              (0.005 0.045)   
                'ref "Wn.c")
            (minOppExtension                 A6              W7                              (0.005 0.045)   
                'ref "Wn.c")
            (minOppExtension                 A7              WT                              (0.005 0.045)   
                'ref "WT.c")
            (minOppExtension                 A2              W2                              (0.005 0.045)   
                'ref "An.c")
            (minOppExtension                 A3              W3                              (0.005 0.045)   
                'ref "An.c")
            (minOppExtension                 A4              W4                              (0.005 0.045)   
                'ref "An.c")
            (minOppExtension                 A5              W5                              (0.005 0.045)   
                'ref "An.c")
            (minOppExtension                 A6              W6                              (0.005 0.045)   
                'ref "An.c")
            (minOppExtension                 A7              W7                              (0.005 0.045)   
                'ref "An.c")
            (minOppExtension                 AT              WT                              (0.02 0.11)     
                'ref "AT.c")
        ) ;orderedSpacings

        spacingTables(
;           ( constraint                      layer1          layer2          layer3          
;               ( (index1Definitions [index2Definitions]) [defaultValue] )
;               ( table ) )
;           ( ---------------------------------------------------------- )
            ( minSpacing                      A1                              
                ( ( "width" nil nil ) 0.165 )
                (
                    0 0.165
                    0.27 0.2
                    10 0.45
                )
            )
            ( minSpacing                      A2                              
                ( ( "width" nil nil ) 0.185 )
                (
                    0 0.185
                    2.0 0.225
                    10 0.45
                )
            )
            ( minSpacing                      A3                              
                ( ( "width" nil nil ) 0.185 )
                (
                    0 0.185
                    2.0 0.225
                    10 0.45
                )
            )
            ( minSpacing                      A4                              
                ( ( "width" nil nil ) 0.185 )
                (
                    0 0.185
                    2.0 0.225
                    10 0.45
                )
            )
            ( minSpacing                      A5                              
                ( ( "width" nil nil ) 0.185 )
                (
                    0 0.185
                    2.0 0.225
                    10 0.45
                )
            )
            ( minSpacing                      A6                              
                ( ( "width" nil nil ) 0.185 )
                (
                    0 0.185
                    2.0 0.225
                    10 0.45
                )
            )
            ( minSpacing                      A7                              
                ( ( "width" nil nil ) 0.185 )
                (
                    0 0.185
                    2.0 0.225
                    10 0.45
                )
            )
            ( minSpacing                      AT                              
                ( ( "width" nil nil ) 0.42 )
                (
                    0 0.42
                    10 0.6
                )
            )
        ) ;spacingTables

        interconnect(
             ( errorLayer		sn_ovlp_sp		'ref "SN_SP.note")
             ( errorLayer		w1_err		'ref "W1.note1")

        ) ;interconnect

    ) ;foundry

    ( "virtuosoDefaultExtractorSetup"

        interconnect(
            (validLayers   (TB  TO  GT  W1  A1  W2  A2  W3  A3  W4 A4 W5 A5 W6 A6 W7 A7  WT  AT  ))

        ) ;interconnect

    ) ;virtuosoDefaultExtractorSetup

    ( "virtuosoDefaultSetup"

        interconnect(
            (validLayers   (GT  A1  A2  A3  A4  A5 A6 A7 AT))
            (validVias      (NDIFF_M1  PDIFF_M1  POLY_M1  M1_M2  M2_M3  M3_M4  M4_M5  M5_M6 M6_M7 M7_MT ))

        ) ;interconnect

    ) ;virtuosoDefaultSetup

    ( "VLMDefaultSetup"

        interconnect(
            (validVias     (POLY_M1  M1_M2  M2_M3  M3_M4  M4_M5 M5_M6 M6_M7 M7_MT ))

        ) ;interconnect

    ) ;VLMDefaultSetup

    ( "LEFDefaultRouteSpec"

        routingGrids(
            ( verticalPitch            	"A1"   0.305 )
            ( horizontalPitch            	"A1"   0.305 )
            ( verticalOffset             	"A1"   0.153 )
            ( horizontalOffset           	"A1"   0.153 )
            ( verticalPitch              	"A2"   0.365 )
            ( horizontalPitch            	"A2"   0.365 )
            ( verticalOffset             	"A2"   0.183 )
            ( horizontalOffset           	"A2"   0.183 )
            ( verticalPitch              	"A3"   0.365 )
            ( horizontalPitch            	"A3"   0.365 )
            ( verticalOffset             	"A3"   0.183 )
            ( horizontalOffset           	"A3"   0.183 )
            ( verticalPitch              	"A4"   0.365 )
            ( horizontalPitch            	"A4"   0.365 )
            ( verticalOffset             	"A4"   0.183 )
            ( horizontalOffset           	"A4"   0.183 )
            ( verticalPitch              	"A5"   0.365 )
            ( horizontalPitch            	"A5"   0.365 )
            ( verticalOffset             	"A5"   0.183 )
            ( horizontalOffset           	"A5"   0.183 )
            ( verticalPitch              	"A6"   0.365 )
            ( horizontalPitch            	"A6"   0.365 )
            ( verticalOffset             	"A6"   0.183 )
            ( horizontalOffset           	"A6"   0.183 )
            ( verticalPitch              	"A7"   0.365 )
            ( horizontalPitch            	"A7"   0.365 )
            ( verticalOffset             	"A7"   0.183 )
            ( horizontalOffset           	"A7"   0.183 )
            ( verticalPitch              	"AT"   0.82 )
            ( horizontalPitch            	"AT"   0.82 )
            ( verticalOffset             	"AT"   0.41 )
            ( horizontalOffset           	"AT"   0.41 )

        ) ;routingGrids

        interconnect(
            (validLayers   (A1  A2  A3  A4  A5 A6 A7 AT  ))
            (validVias      (M1_M2  M2_M3 M3_M4 M4_M5 M5_M6 M6_M7 M7_MT ))

        ) ;interconnect

    ) ;LEFDefaultRouteSpec

) ;constraintGroups


devices(

multipartPathTemplates(
; ( name [masterPath] [offsetSubpaths] [encSubPaths] [subRects] )
; 
;   masterPath:
;   (layer [width] [choppable] [endType] [beginExt] [endExt] [justify] [offset]
;   [connectivity])
; 
;   offsetSubpaths:
;   (layer [width] [choppable] [separation] [justification] [begOffset] [endOffset]
;   [connectivity])
; 
;   encSubPaths:
;   (layer [enclosure] [choppable] [separation] [begOffset] [endOffset]
;   [connectivity])
; 
;   subRects:
;   (layer [width] [length] [choppable] [separation] [justification] [space] [begOffset] [endOffset] [gap] 
;   [connectivity] [beginSegOffset] [endSegOffset])
; 
;   connectivity:
;   ([I/O type] [pin] [accDir] [dispPinName] [height] [ layer]
;    [layer] [justification] [font] [textOptions] [orientation]
;    [refHandle] [offset])
; 
; ( --------------------------------------------------------------------- )
  (PsubGuardRing 
    (("TO" "drawing")	0.26	t	truncate  	0.0)
    (
     (("A1" "drawing")	0.14	t	0.0	center    	0         	0         )
     (("SP" "drawing")	0.58	t	0       center    	0         	0         )
    )
    nil
    (
     (("W1" "drawing")	0.14	0.14	t	0.0	center	0.165	-0.1	-0.1	distribute	nil	0.0	0.0)
    )
  )
  (NwellGuardRing
    (("TO" "drawing")	0.26	t	truncate  	0.0)
    (
     (("A1" "drawing")	0.14	t	0.0	center    	0         	0         )
     (("SN" "drawing")	0.58	t	0       center    	0         	0         )
    )
    nil
    (
     (("W1" "drawing")	0.14	0.14	t	0.0	center	0.165	-0.1	-0.1	distribute	nil	0.0	0.0)
    )
  )
)  ;multipartPathTemplates


) ;devices


