; Technology File 1P8M_7Ic_1MTTc_ALPA
; Generated on Mar 20 17:39:51 2016
;     with @(#)$CDS: virtuoso version 6.1.6-64b 02/17/2014 20:33 (sjfnl178) $


;********************************
; CONTROLS
;********************************
controls(
 techVersion("1.0")

 techParams(
 ;( parameter    value )
  ( CT_2      0.18 )
  ( CT_5      0.06 )
  ( CT_6      0.06 )
  ( CT_7      0.00 )
  ( CT_8      0.05 )
  ( V1_2      0.25 )
  ( V1_4      0.005 )
  ( V1_5      0.05 )
  ( V1_6      0.005 )
  ( V1_7      0.03 )
  ( Vn_2      0.25 )
  ( Vn_3      0.005 )
  ( Vn_4      0.05 )
  ( Vn_5      0.005 )
  ( Vn_6      0.03 )
  ( TV_2      0.5 )
  ( TV_4      0.01 )
  ( TV_5      0.05 )
  ( TV_6      0.03 )
  ( TV_7      0.07 )
  ( TM_1      0.42 )
  ( TM_5      0.42 )
  ( MTT_3     0.30 )
  ( MTT_4     0.42 )
  ( MTT_1     1.50 )
  ( MTT_6     2.25 )
  ( PA_2      7.0  )
  ( PA_3      1.50 )
  ( PA_4      1.50 )
 ) ;techParams

 viewTypeUnits(
 ;( viewType            userUnit       dbuperuu           )
 ;( --------            --------       --------           )
  ( maskLayout     	"micron"       	1000            )
  ( schematic      	"inch"         	160             )
  ( schematicSymbol	"inch"         	160             )
  ( netlist        	"inch"         	160             )
 ) ;viewTypeUnits

 mfgGridResolution(
      ( 0.005000 )
 ) ;mfgGridResolution

) ;controls


;********************************
; LAYER DEFINITION
;********************************
layerDefinitions(

 techPurposes(
 ;( PurposeName               Purpose#   Abbreviation )
 ;( -----------               --------   ------------ )
 ;User-Defined Purposes:
  ( metal1                    1          m1           )
  ( metal2                    2          m2           )
  ( metal3                    3          m3           )
  ( metal4                    4          m4           )
  ( metal5                    5          m5           )
  ( metal6                    6          m6           )
  ( metal7                    7          m7           )
  ( metal8                    8          m8           )
  ( topmetal1                 9          tm1          )
  ( topmetal2                 10         tm2          )
  ( stsram                    34         sts          )
  ( dnsram                    35         dns          )
  ( udsram                    36         uds          )
  ( dpsram                    37         dps          )
  ( lrsram                    38         lrs          )
  ( markg                     48         mkg          )
  ( marks                     49         mks          )
  ( markf                     50         mkf          )
  ( mk1                       51         mk1          )
  ( mk2                       52         mk2          )
  ( mk3                       53         mk3          )
  ( mk4                       54         mk4          )
  ( mk5                       55         mk5          )
  ( mk6                       56         mk6          )
  ( mk7                       57         mk7          )
  ( mk8                       58         mk8          )
 ;System-Reserved Purposes:
  ( warning                   234        wng          )
  ( tool1                     235        tl1          )
  ( tool0                     236        tl0          )
  ( label                     237        lbl          )
  ( flight                    238        flt          )
  ( error                     239        err          )
  ( annotate                  240        ant          )
  ( drawing1                  241        dr1          )
  ( drawing2                  242        dr2          )
  ( drawing3                  243        dr3          )
  ( drawing4                  244        dr4          )
  ( drawing5                  245        dr5          )
  ( drawing6                  246        dr6          )
  ( drawing7                  247        dr7          )
  ( drawing8                  248        dr8          )
  ( drawing9                  249        dr9          )
  ( boundary                  250        bnd          )
  ( pin                       251        pin          )
  ( net                       253        net          )
  ( cell                      254        cel          )
  ( all                       255        all          )
 ) ;techPurposes

 techLayers(
 ;( LayerName                 Layer#     Abbreviation )
 ;( ---------                 ------     ------------ )
 ;User-Defined Layers:
  ( GTDUM                     0          GTDUM        )
  ( "0M"                      1          "0M"         )
  ( M1DUM                     2          M1DUM        )
  ( AADUM                     3          AADUM        )
  ( PFL                       4          PFL          )
  ( LUWMK1                    5          LUWMK1       )
  ( VDDMK1                    6          VDDMK1       )
  ( VSSMK1                    7          VSSMK1       )
  ( CO                        8          CO           )
  ( KV                        9          KV           )
  ( AA                        10         AA           )
  ( TM2TXT                    11         TM2TXT       )
  ( NPAA                      12         NPAA         )
  ( PPAA                      13         PPAA         )
  ( NW                        14         NW           )
  ( TP                        15         TP           )
  ( PC                        16         PC           )
  ( RESP3T                    17         RESP3T       )
  ( CL                        18         CL           )
  ( DNW                       19         DNW          )
  ( PW                        20         PW           )
  ( NC                        21         NC           )
  ( CPT                       22         CPT          )
  ( BNP                       23         BNP          )
  ( TN                        24         TN           )
  ( CODE                      25         CODE         )
  ( LOGO                      26         LOGO         )
  ( CCT                       27         CCT          )
  ( BC                        28         BC           )
  ( DG                        29         DG           )
  ( GT                        30         GT           )
  ( P2                        31         P2           )
  ( P3                        32         P3           )
  ( P4                        33         P4           )
  ( HR                        34         HR           )
  ( NLL                       35         NLL          )
  ( NLH                       36         NLH          )
  ( PLH                       37         PLH          )
  ( PLL                       38         PLL          )
  ( HRP                       39         HRP          )
  ( SN                        40         SN           )
  ( ESD1                      41         ESD1         )
  ( ESD2                      42         ESD2         )
  ( SP                        43         SP           )
  ( MVP                       44         MVP          )
  ( MVN                       45         MVN          )
  ( VTPH                      46         VTPH         )
  ( VTNH                      47         VTNH         )
  ( SAB                       48         SAB          )
  ( IDT                       49         IDT          )
  ( CT                        50         CT           )
  ( CM                        51         CM           )
  ( M2DUM                     52         M2DUM        )
  ( DDN                       53         DDN          )
  ( HVBN                      54         HVBN         )
  ( NDDD                      55         NDDD         )
  ( DDP                       56         DDP          )
  ( STIDMY                    57         STIDMY       )
  ( MIM                       58         MIM          )
  ( M0                        59         M0           )
  ( INST                      60         INST         )
  ( M1                        61         M1           )
  ( M2                        62         M2           )
  ( M3                        63         M3           )
  ( M4                        64         M4           )
  ( M5                        65         M5           )
  ( M6                        66         M6           )
  ( M7                        67         M7           )
  ( M8                        68         M8           )
  ( M3DUM                     69         M3DUM        )
  ( V1                        70         V1           )
  ( V2                        71         V2           )
  ( V3                        72         V3           )
  ( V4                        73         V4           )
  ( V5                        74         V5           )
  ( V6                        75         V6           )
  ( V7                        76         V7           )
  ( DUPMK1                    77         DUPMK1       )
  ( M4DUM                     78         M4DUM        )
  ( PIPR                      79         PIPR         )
  ( PA                        80         PA           )
  ( FUSE                      81         FUSE         )
  ( PI                        82         PI           )
  ( ALPA                      83         ALPA         )
  ( PLDMK                     84         PLDMK        )
  ( PSUB                      85         PSUB         )
  ( VSIA                      86         VSIA         )
  ( TTXT                      87         TTXT         )
  ( BTXT                      88         BTXT         )
  ( CTXT                      89         CTXT         )
  ( DUMBM                     90         DUMBM        )
  ( DUMBA                     91         DUMBA        )
  ( DUMBP                     92         DUMBP        )
  ( VARMOS                    93         VARMOS       )
  ( VARJUN                    94         VARJUN       )
  ( RESNW                     95         RESNW        )
  ( RESP1                     96         RESP1        )
  ( RESAA                     97         RESAA        )
  ( SUBD                      98         SUBD         )
  ( M5DUM                     99         M5DUM        )
  ( OPCBA                     100        OPCBA        )
  ( OPCBP                     101        OPCBP        )
  ( OPCBM                     102        OPCBM        )
  ( NDRF                      103        NDRF         )
  ( PDRF                      104        PDRF         )
  ( PWH                       105        PWH          )
  ( NWH                       106        NWH          )
  ( PPCI                      107        PPCI         )
  ( NPCI                      108        NPCI         )
  ( PWHT                      109        PWHT         )
  ( NWHT                      110        NWHT         )
  ( DNWTR                     111        DNWTR        )
  ( RF3T                      112        RF3T         )
  ( PIP                       113        PIP          )
  ( RFDN6T                    114        RFDN6T       )
;  ( EXDFM                     115        EXDFM        )
  ( MIMSTK                    116        MIMSTK       )
;  ( EXLFD                     117        EXLFD        )
  ( MARK                      118        MARK         )
  ( TM1DUM                    119        TM1DUM       )
  ( TM1                       120        TM1          )
  ( TV1                       121        TV1          )
  ( TM2                       122        TM2          )
  ( TV2                       123        TV2          )
  ( TM2DUM                    124        TM2DUM       )
  ( TG                        125        TG           )
  ( TM1TXT                    126        TM1TXT       )
  ( BORDER                    127        BORDER       )
  ( M6DUM                     128        M6DUM        )
  ( NFDMK                     129        NFDMK        )
  ( M7DUM                     130        M7DUM        )
  ( HTNWL                     131        HTNWL        )
  ( EXCLU                     132        EXCLU        )
  ( ESDIO1                    133        ESDIO1       )
  ( DMPNP                     134        DMPNP        )
  ( PDC                       135        PDC          )
;  ( PWL                       136        PWL          )
  ( CAPBP                     137        CAPBP        )
  ( DSTR                      138        DSTR         )
  ( DCTY                      139        DCTY         )
  ( SBT                       140        SBT          )
  ( M1TXT                     141        M1TXT        )
  ( M2TXT                     142        M2TXT        )
  ( M3TXT                     143        M3TXT        )
  ( M4TXT                     144        M4TXT        )
  ( M5TXT                     145        M5TXT        )
  ( M6TXT                     146        M6TXT        )
  ( M7TXT                     147        M7TXT        )
  ( M8TXT                     148        M8TXT        )
  ( ESD5V                     149        ESD5V        )
  ( MOSCKT                    150        MOSCKT       )
  ( MnB                       151        MnB          )
  ( MnDUB                     152        MnDUB        )
  ( RESCKT                    153        RESCKT       )
  ( ALPAR                     154        ALPAR        )
  ( ALPATXT                   155        ALPATXT      )
  ( ALRDL                     156        ALRDL        )
  ( MOMDMY                    157        MOMDMY       )
  ( SRAM                      158        SRAM         )
;  ( JVDUM                     159        JVDUM        )
  ( M8DUM                     160        M8DUM        )
  ( SUBTXT                    161        SUBTXT       )
  ( WELTXT                    162        WELTXT       )
  ( DIFTXT                    163        DIFTXT       )
  ( POLYTXT                   164        POLYTXT      )
  ( BCB1                      165        BCB1         )
  ( RDL                       166        RDL          )
  ( BCB2                      167        BCB2         )
  ( BUMP                      168        BUMP         )
  ( RFSD                      169        RFSD         )
  ( POWRING                   170        POWRING      )
  ( MnR                       171        MnR          )
  ( MnSLOTB                   172        MnSLOTB      )
  ( MnSLOT                    173        MnSLOT       )
  ( MIMCKT                    174        MIMCKT       )
  ( MIMSHD                    175        MIMSHD       )
  ( INDR                      176        INDR         )
  ( GTFUSE                    177        GTFUSE       )
  ( DDNW                      178        DDNW         )
  ( ESDIO2                    179        ESDIO2       )
  ( NODMF                     180        NODMF        )
  ( HRPDMY                    181        HRPDMY       )
  ( EFUSE                     182        EFUSE        )
  ( CLPDMY                    183        CLPDMY       )
  ( DMRES                     184        DMRES        )
  ( RP185                     185        RP185        )
  ( SURNW                     186        SURNW        )
  ( ALMK1                     187        ALMK1        )
  ( MIMDMY                    189        MIMDMY       )
  ( INDMY                     190        INDMY        )
  ( RFDEV                     191        RFDEV        )
  ( RFMOSD                    192        RFMOSD       )
  ( JVARDUM                   193        JVARDUM      )
  ( MD                        194        MD           )
 ;System-Reserved Layers:
  ( Unrouted                  200        Unroute      )
  ( Row                       201        Row          )
  ( Group                     202        Group        )
  ( Cannotoccupy              203        noOcupy      )
  ( Canplace                  204        Canplac      )
  ( hardFence                 205        hardFnc      )
  ( softFence                 206        softFnc      )
  ( y0                        207        y0           )
  ( y1                        208        y1           )
  ( y2                        209        y2           )
  ( y3                        210        y3           )
  ( y4                        211        y4           )
  ( y5                        212        y5           )
  ( y6                        213        y6           )
  ( y7                        214        y7           )
  ( y8                        215        y8           )
  ( y9                        216        y9           )
  ( designFlow                217        dsnFlow      )
  ( stretch                   218        stretch      )
  ( edgeLayer                 219        edgeLyr      )
  ( changedLayer              220        chngLyr      )
  ( unset                     221        unset        )
  ( unknown                   222        unknown      )
  ( spike                     223        spike        )
  ( hiz                       224        hiz          )
  ( resist                    225        resist       )
  ( drive                     226        drive        )
  ( supply                    227        supply       )
  ( wire                      228        wire         )
  ( pin                       229        pin          )
  ( text                      230        text         )
  ( device                    231        device       )
  ( border                    232        border       )
  ( snap                      233        snap         )
  ( align                     234        align        )
  ( prBoundary                235        prBndry      )
  ( instance                  236        instnce      )
  ( annotate                  237        anotate      )
  ( marker                    238        marker       )
  ( select                    239        select       )
  ( grid                      251        grid         )
  ( axis                      252        axis         )
  ( hilite                    253        hilite       )
  ( background                254        bkground     )
 ) ;techLayers

 techLayerPurposePriorities(
 ;layers are ordered from lowest to highest priority
 ;( LayerName                 Purpose    )
 ;( ---------                 -------    )
  ( "0M"                      drawing    )
  ( LUWMK1                    drawing    )
  ( VDDMK1                    drawing    )
  ( VSSMK1                    drawing    )
  ( CO                        drawing    )
  ( KV                        drawing    )
  ( AA                        drawing    )
  ( AADUM                     drawing    )
  ( TG                        drawing    )
  ( NPAA                      drawing    )
  ( PPAA                      drawing    )
  ( NW                        drawing    )
  ( TP                        drawing    )
  ( PC                        drawing    )
  ( CL                        drawing    )
  ( DNW                       drawing    )
  ( DNWTR                     drawing    )
  ( PW                        drawing    )
  ( NC                        drawing    )
  ( CPT                       drawing    )
  ( BNP                       drawing    )
  ( TN                        drawing    )
  ( CODE                      drawing    )
  ( LOGO                      drawing    )
  ( BC                        drawing    )
  ( DG                        drawing    )
  ( GT                        drawing    )
  ( GTDUM                     drawing    )
  ( P2                        drawing    )
  ( P3                        drawing    )
  ( P4                        drawing    )
  ( HR                        drawing    )
  ( NLL                       drawing    )
  ( NLH                       drawing    )
  ( PLH                       drawing    )
  ( PLL                       drawing    )
  ( HRP                       drawing    )
  ( SN                        drawing    )
  ( SP                        drawing    )
  ( ESD1                      drawing    )
  ( ESD2                      drawing    )
  ( MVP                       drawing    )
  ( MVN                       drawing    )
  ( VTPH                      drawing    )
  ( VTNH                      drawing    )
  ( SAB                       drawing    )
  ( IDT                       drawing    )
  ( CT                        drawing    )
  ( CM                        drawing    )
  ( DDN                       drawing    )
  ( HVBN                      drawing    )
  ( NDDD                      drawing    )
  ( DDP                       drawing    )
  ( MIM                       drawing    )
  ( M0                        drawing    )
  ( INST                      drawing    )
  ( M1                        drawing    )
  ( M2                        drawing    )
  ( M3                        drawing    )
  ( M4                        drawing    )
  ( M5                        drawing    )
  ( M6                        drawing    )
  ( M7                        drawing    )
  ( M8                        drawing    )
  ( M1DUM                     drawing    )
  ( M2DUM                     drawing    )
  ( M3DUM                     drawing    )
  ( M4DUM                     drawing    )
  ( M5DUM                     drawing    )
  ( M6DUM                     drawing    )
  ( M7DUM                     drawing    )
  ( M8DUM                     drawing    )
  ( V1                        drawing    )
  ( V2                        drawing    )
  ( V3                        drawing    )
  ( V4                        drawing    )
  ( V5                        drawing    )
  ( V6                        drawing    )
  ( V7                        drawing    )
  ( PIPR                      drawing    )
  ( PA                        drawing    )
  ( FUSE                      drawing    )
  ( PI                        drawing    )
  ( ALPA                      drawing    )
  ( ALPAR                     drawing    )
  ( ALPATXT                   drawing    )
  ( ALRDL                     drawing    )
  ( PSUB                      drawing    )
  ( VSIA                      drawing    )
  ( TTXT                      drawing    )
  ( BTXT                      drawing    )
  ( CTXT                      drawing    )
  ( DUMBM                     drawing    )
  ( DUMBA                     drawing    )
  ( DUMBP                     drawing    )
  ( VARMOS                    drawing    )
  ( VARJUN                    drawing    )
  ( RESNW                     drawing    )
  ( RESP1                     drawing    )
  ( RESP3T                    drawing    )
  ( RESAA                     drawing    )
  ( RESCKT                    drawing    )
  ( MOSCKT                    drawing    )
  ( PFL                       drawing    )
  ( OPCBA                     drawing    )
  ( OPCBP                     drawing    )
  ( OPCBM                     drawing    )
  ( NDRF                      drawing    )
  ( PDRF                      drawing    )
  ( BORDER                    drawing    )
  ( SUBD                      drawing    )
  ( HTNWL                     drawing    )
  ( EXCLU                     drawing    )
  ( PPCI                      drawing    )
  ( NPCI                      drawing    )
  ( PWHT                      drawing    )
  ( NWHT                      drawing    )
  ( PIP                       drawing    )
  ( TM1                       drawing    )
  ( TM1DUM                    drawing    )
  ( TM1TXT                    drawing    )
  ( TV1                       drawing    )
  ( TM2                       drawing    )
  ( TM2DUM                    drawing    )
  ( TM2TXT                    drawing    )
  ( TV2                       drawing    )
  ( ESDIO1                    drawing    )
  ( ESD5V                     drawing    )
  ( POWRING                   drawing    )
  ( ESDIO2                    drawing    )
  ( DMPNP                     drawing    )
  ( PDC                       drawing    )
  ( CAPBP                     drawing    )
  ( DSTR                      drawing    )
  ( DCTY                      drawing    )
  ( SBT                       drawing    )
  ( M1TXT                     drawing    )
  ( M2TXT                     drawing    )
  ( M3TXT                     drawing    )
  ( M4TXT                     drawing    )
  ( M5TXT                     drawing    )
  ( M6TXT                     drawing    )
  ( M7TXT                     drawing    )
  ( M8TXT                     drawing    )
  ( SUBTXT                    drawing    )
  ( WELTXT                    drawing    )
  ( DIFTXT                    drawing    )
  ( POLYTXT                   drawing    )
  ( BCB1                      drawing    )
  ( RDL                       drawing    )
  ( BCB2                      drawing    )
  ( BUMP                      drawing    )
  ( MnB                       metal1     )
  ( MnB                       metal2     )
  ( MnB                       metal3     )
  ( MnB                       metal4     )
  ( MnB                       metal5     )
  ( MnB                       metal6     )
  ( MnB                       metal7     )
  ( MnB                       metal8     )
  ( MnB                       topmetal1  )
  ( MnB                       topmetal2  )
  ( MnDUB                     metal1     )
  ( MnDUB                     metal2     )
  ( MnDUB                     metal3     )
  ( MnDUB                     metal4     )
  ( MnDUB                     metal5     )
  ( MnDUB                     metal6     )
  ( MnDUB                     metal7     )
  ( MnDUB                     metal8     )
  ( MnDUB                     topmetal1  )
  ( MnDUB                     topmetal2  )
  ( PWH                       drawing    )
  ( NWH                       drawing    )
  ( MnR                       metal1     )
  ( MnR                       metal2     )
  ( MnR                       metal3     )
  ( MnR                       metal4     )
  ( MnR                       metal5     )
  ( MnR                       metal6     )
  ( MnR                       metal7     )
  ( MnR                       metal8     )
  ( MnR                       topmetal1  )
  ( MnR                       topmetal2  )
  ( MnSLOTB                   metal1     )
  ( MnSLOTB                   metal2     )
  ( MnSLOTB                   metal3     )
  ( MnSLOTB                   metal4     )
  ( MnSLOTB                   metal5     )
  ( MnSLOTB                   metal6     )
  ( MnSLOTB                   metal7     )
  ( MnSLOTB                   metal8     )
  ( MnSLOT                    metal1     )
  ( MnSLOT                    metal2     )
  ( MnSLOT                    metal3     )
  ( MnSLOT                    metal4     )
  ( MnSLOT                    metal5     )
  ( MnSLOT                    metal6     )
  ( MnSLOT                    metal7     )
  ( MnSLOT                    metal8     )
  ( MnSLOT                    topmetal1  )
  ( MnSLOT                    topmetal2  )
  ( MIMCKT                    drawing    )
  ( MIMSHD                    drawing    )
  ( INDR                      drawing    )
  ( GTFUSE                    drawing    )
  ( EFUSE                     drawing    )
  ( CLPDMY                    drawing    )
  ( DMRES                     drawing    )
  ( SURNW                     drawing    )
  ( DDNW                      drawing    )
  ( NODMF                     drawing    )
  ( HRPDMY                    drawing    )
  ( MIMDMY                    drawing    )
  ( MOMDMY                    drawing    )
  ( MOMDMY                    mk1        )
  ( MOMDMY                    mk2        )
  ( MOMDMY                    mk3        )
  ( MOMDMY                    mk4        )
  ( MOMDMY                    mk5        )
  ( MOMDMY                    mk6        )
  ( MOMDMY                    mk7        )
  ( MOMDMY                    mk8        )
  ( INDMY                     drawing    )
  ( RFDEV                     drawing    )
  ( RFMOSD                    drawing    )
  ( JVARDUM                   drawing    )
  ( MD                        drawing    )
  ( RF3T                      drawing    )
  ( RP185                     drawing    )
  ( CCT                       drawing    )
  ( PLDMK                     drawing    )
  ( NFDMK                     drawing    )
  ( SRAM                      stsram     )
  ( SRAM                      dnsram     )
  ( SRAM                      udsram     )
  ( SRAM                      dpsram     )
  ( SRAM                      lrsram     )
  ( RFSD                      drawing    )
  ( RFDN6T                    drawing    )
  ( MIMSTK                    drawing    )
  ( STIDMY                    drawing    )
  ( MARK                      markg      )
  ( MARK                      marks      )
  ( MARK                      markf      )
  ( DUPMK1                    drawing    )
  ( FUSE                      mk1        )
  ( ALMK1                     drawing    )
  ( background                drawing    )
  ( grid                      drawing    )
  ( grid                      drawing1   )
  ( annotate                  drawing    )
  ( annotate                  drawing1   )
  ( annotate                  drawing2   )
  ( annotate                  drawing3   )
  ( annotate                  drawing4   )
  ( annotate                  drawing5   )
  ( annotate                  drawing6   )
  ( annotate                  drawing7   )
  ( annotate                  drawing8   )
  ( annotate                  drawing9   )
  ( instance                  drawing    )
  ( instance                  label      )
  ( prBoundary                drawing    )
  ( prBoundary                boundary   )
  ( prBoundary                label      )
  ( align                     drawing    )
  ( hardFence                 drawing    )
  ( softFence                 drawing    )
  ( text                      drawing    )
  ( text                      drawing1   )
  ( text                      drawing2   )
  ( border                    drawing    )
  ( device                    drawing    )
  ( device                    label      )
  ( device                    drawing1   )
  ( device                    drawing2   )
  ( device                    annotate   )
  ( wire                      drawing    )
  ( wire                      label      )
  ( wire                      flight     )
  ( pin                       label      )
  ( pin                       drawing    )
  ( pin                       annotate   )
  ( axis                      drawing    )
  ( edgeLayer                 drawing    )
  ( edgeLayer                 pin        )
  ( snap                      drawing    )
  ( stretch                   drawing    )
  ( y0                        drawing    )
  ( y1                        drawing    )
  ( y2                        drawing    )
  ( y3                        drawing    )
  ( y4                        drawing    )
  ( y5                        drawing    )
  ( y6                        drawing    )
  ( y7                        drawing    )
  ( y8                        drawing    )
  ( y9                        drawing    )
  ( hilite                    drawing    )
  ( hilite                    drawing1   )
  ( hilite                    drawing2   )
  ( hilite                    drawing3   )
  ( hilite                    drawing4   )
  ( hilite                    drawing5   )
  ( hilite                    drawing6   )
  ( hilite                    drawing7   )
  ( hilite                    drawing8   )
  ( hilite                    drawing9   )
  ( select                    drawing    )
  ( drive                     drawing    )
  ( hiz                       drawing    )
  ( resist                    drawing    )
  ( spike                     drawing    )
  ( supply                    drawing    )
  ( unknown                   drawing    )
  ( unset                     drawing    )
  ( designFlow                drawing    )
  ( designFlow                drawing1   )
  ( designFlow                drawing2   )
  ( designFlow                drawing3   )
  ( designFlow                drawing4   )
  ( designFlow                drawing5   )
  ( designFlow                drawing6   )
  ( designFlow                drawing7   )
  ( designFlow                drawing8   )
  ( designFlow                drawing9   )
  ( changedLayer              tool0      )
  ( changedLayer              tool1      )
  ( marker                    warning    )
  ( marker                    error      )
  ( Row                       drawing    )
  ( Row                       label      )
  ( Group                     drawing    )
  ( Group                     label      )
  ( Cannotoccupy              drawing    )
  ( Cannotoccupy              boundary   )
  ( Canplace                  drawing    )
  ( Unrouted                  drawing    )
  ( Unrouted                  drawing1   )
  ( Unrouted                  drawing2   )
  ( Unrouted                  drawing3   )
  ( Unrouted                  drawing4   )
  ( Unrouted                  drawing5   )
  ( Unrouted                  drawing6   )
  ( Unrouted                  drawing7   )
  ( Unrouted                  drawing8   )
  ( Unrouted                  drawing9   )
  ( snap                      boundary   )
 ) ;techLayerPurposePriorities

 techDisplays(
 ;( LayerName    Purpose      Packet          Vis Sel Con2ChgLy DrgEnbl Valid )
 ;( ---------    -------      ------          --- --- --------- ------- ----- )
  ( "0M"         drawing      "0m"             t t t t t )
  ( LUWMK1       drawing      luwmk1           t t t t t )
  ( VDDMK1       drawing      vddmk1           t t t t t )
  ( VSSMK1       drawing      vssmk1           t t t t t )
  ( CO           drawing      co               t t t t t )
  ( KV           drawing      kv               t t t t t )
  ( AA           drawing      aa               t t t t t )
  ( AADUM        drawing      aadum            t t t t t )
  ( TG           drawing      tg               t t t t t )
  ( NPAA         drawing      npaa             t t t t t )
  ( PPAA         drawing      ppaa             t t t t t )
  ( NW           drawing      nw               t t t t t )
  ( TP           drawing      tp               t t t t t )
  ( PC           drawing      pc               t t t t t )
  ( CL           drawing      cl               t t t t t )
  ( DNW          drawing      dnw              t t t t t )
  ( DNWTR        drawing      dnwtr            t t t t t )
  ( PW           drawing      pw               t t t t t )
  ( NC           drawing      nc               t t t t t )
  ( CPT          drawing      cpt              t t t t t )
  ( BNP          drawing      bnp              t t t t t )
  ( TN           drawing      tn               t t t t t )
  ( CODE         drawing      code             t t t t t )
  ( LOGO         drawing      logo             t t t t t )
  ( BC           drawing      bc               t t t t t )
  ( DG           drawing      dg               t t t t t )
  ( GT           drawing      gt               t t t t t )
  ( GTDUM        drawing      gtdum            t t t t t )
  ( P2           drawing      p2               t t t t t )
  ( P3           drawing      p3               t t t t t )
  ( P4           drawing      p4               t t t t t )
  ( HR           drawing      hr               t t t t t )
  ( NLL          drawing      nll              t t t t t )
  ( NLH          drawing      nlh              t t t t t )
  ( PLH          drawing      plh              t t t t t )
  ( PLL          drawing      pll              t t t t t )
  ( HRP          drawing      hrp              t t t t t )
  ( SN           drawing      sn               t t t t t )
  ( SP           drawing      sp               t t t t t )
  ( ESD1         drawing      esd1             t t t t t )
  ( ESD2         drawing      esd2             t t t t t )
  ( MVP          drawing      mvp              t t t t t )
  ( MVN          drawing      mvn              t t t t t )
  ( VTPH         drawing      vtph             t t t t t )
  ( VTNH         drawing      vtnh             t t t t t )
  ( SAB          drawing      sab              t t t t t )
  ( IDT          drawing      idt              t t t t t )
  ( CT           drawing      ct               t t t t t )
  ( CM           drawing      cm               t t t t t )
  ( DDN          drawing      ddn              t t t t t )
  ( HVBN         drawing      hvbn             t t t t t )
  ( NDDD         drawing      nddd             t t t t t )
  ( DDP          drawing      ddp              t t t t t )
  ( MIM          drawing      mim              t t t t t )
  ( M0           drawing      m0               t t t t t )
  ( INST         drawing      inst             t t t t t )
  ( M1           drawing      m1               t t t t t )
  ( M2           drawing      m2               t t t t t )
  ( M3           drawing      m3               t t t t t )
  ( M4           drawing      m4               t t t t t )
  ( M5           drawing      m5               t t t t t )
  ( M6           drawing      m6               t t t t t )
  ( M7           drawing      m7               t t t t t )
  ( M8           drawing      m8               t t t t t )
  ( M1DUM        drawing      m1dum            t t t t t )
  ( M2DUM        drawing      m2dum            t t t t t )
  ( M3DUM        drawing      m3dum            t t t t t )
  ( M4DUM        drawing      m4dum            t t t t t )
  ( M5DUM        drawing      m5dum            t t t t t )
  ( M6DUM        drawing      m6dum            t t t t t )
  ( M7DUM        drawing      m7dum            t t t t t )
  ( M8DUM        drawing      m8dum            t t t t t )
  ( V1           drawing      v1               t t t t t )
  ( V2           drawing      v2               t t t t t )
  ( V3           drawing      v3               t t t t t )
  ( V4           drawing      v4               t t t t t )
  ( V5           drawing      v5               t t t t t )
  ( V6           drawing      v6               t t t t t )
  ( V7           drawing      v7               t t t t t )
  ( PIPR         drawing      pipr             t t t t t )
  ( PA           drawing      pa               t t t t t )
  ( FUSE         drawing      fuse             t t t t t )
  ( PI           drawing      pi               t t t t t )
  ( ALPA         drawing      alpa             t t t t t )
  ( ALPAR        drawing      alpar            t t t t t )
  ( ALPATXT      drawing      alpatxt          t t t t t )
  ( ALRDL        drawing      alrdl            t t t t t )
  ( PSUB         drawing      psub             t t t t t )
  ( VSIA         drawing      vsia             t t t t t )
  ( TTXT         drawing      ttxt             t t t t t )
  ( BTXT         drawing      btxt             t t t t t )
  ( CTXT         drawing      ctxt             t t t t t )
  ( DUMBM        drawing      dumbm            t t t t t )
  ( DUMBA        drawing      dumba            t t t t t )
  ( DUMBP        drawing      dumbp            t t t t t )
  ( VARMOS       drawing      varmos           t t t t t )
  ( VARJUN       drawing      varjun           t t t t t )
  ( RESNW        drawing      resnw            t t t t t )
  ( RESP1        drawing      resp1            t t t t t )
  ( RESP3T       drawing      resp3t           t t t t t )
  ( RESAA        drawing      resaa            t t t t t )
  ( RESCKT       drawing      resckt           t t t t t )
  ( MOSCKT       drawing      mosckt           t t t t t )
  ( PFL          drawing      pfl              t t t t t )
  ( OPCBA        drawing      opcba            t t t t t )
  ( OPCBP        drawing      opcbp            t t t t t )
  ( OPCBM        drawing      opcbm            t t t t t )
  ( NDRF         drawing      ndrf             t t t t t )
  ( PDRF         drawing      pdrf             t t t t t )
  ( BORDER       drawing      border           t t t t t )
  ( SUBD         drawing      subd             t t t t t )
  ( HTNWL        drawing      htnwl            t t t t t )
  ( EXCLU        drawing      exclu            t t t t t )
  ( PPCI         drawing      ppci             t t t t t )
  ( NPCI         drawing      npci             t t t t t )
  ( PWHT         drawing      pwht             t t t t t )
  ( NWHT         drawing      nwht             t t t t t )
  ( PIP          drawing      pip              t t t t t )
  ( TM1          drawing      tm1              t t t t t )
  ( TM1DUM       drawing      tm1dum           t t t t t )
  ( TM1TXT       drawing      tm1txt           t t t t t )
  ( TV1          drawing      tv1              t t t t t )
  ( TM2          drawing      tm2              t t t t t )
  ( TM2DUM       drawing      tm2dum           t t t t t )
  ( TM2TXT       drawing      tm2txt           t t t t t )
  ( TV2          drawing      tv2              t t t t t )
  ( ESDIO1       drawing      esdio1           t t t t t )
  ( ESD5V        drawing      esd5v            t t t t t )
  ( POWRING      drawing      powring          t t t t t )
  ( ESDIO2       drawing      esdio2           t t t t t )
  ( DMPNP        drawing      dmpnp            t t t t t )
  ( PDC          drawing      pdc              t t t t t )
  ( CAPBP        drawing      capbp            t t t t t )
  ( DSTR         drawing      dstr             t t t t t )
  ( DCTY         drawing      dcty             t t t t t )
  ( SBT          drawing      sbt              t t t t t )
  ( M1TXT        drawing      m1txt            t t t t t )
  ( M2TXT        drawing      m2txt            t t t t t )
  ( M3TXT        drawing      m3txt            t t t t t )
  ( M4TXT        drawing      m4txt            t t t t t )
  ( M5TXT        drawing      m5txt            t t t t t )
  ( M6TXT        drawing      m6txt            t t t t t )
  ( M7TXT        drawing      m7txt            t t t t t )
  ( M8TXT        drawing      m8txt            t t t t t )
  ( SUBTXT       drawing      subtxt           t t t t t )
  ( WELTXT       drawing      weltxt           t t t t t )
  ( DIFTXT       drawing      diftxt           t t t t t )
  ( POLYTXT      drawing      polytxt          t t t t t )
  ( BCB1         drawing      bcb1             t t t t t )
  ( RDL          drawing      rdl              t t t t t )
  ( BCB2         drawing      bcb2             t t t t t )
  ( BUMP         drawing      bump             t t t t t )
  ( MnB          metal1       m1b              t t t t t )
  ( MnB          metal2       m2b              t t t t t )
  ( MnB          metal3       m3b              t t t t t )
  ( MnB          metal4       m4b              t t t t t )
  ( MnB          metal5       m5b              t t t t t )
  ( MnB          metal6       m6b              t t t t t )
  ( MnB          metal7       m7b              t t t t t )
  ( MnB          metal8       m8b              t t t t t )
  ( MnB          topmetal1    tm1b             t t t t t )
  ( MnB          topmetal2    tm2b             t t t t t )
  ( MnDUB        metal1       m1dub            t t t t t )
  ( MnDUB        metal2       m2dub            t t t t t )
  ( MnDUB        metal3       m3dub            t t t t t )
  ( MnDUB        metal4       m4dub            t t t t t )
  ( MnDUB        metal5       m5dub            t t t t t )
  ( MnDUB        metal6       m6dub            t t t t t )
  ( MnDUB        metal7       m7dub            t t t t t )
  ( MnDUB        metal8       m8dub            t t t t t )
  ( MnDUB        topmetal1    tm1dub           t t t t t )
  ( MnDUB        topmetal2    tm2dub           t t t t t )
  ( PWH          drawing      pwh              t t t t t )
  ( NWH          drawing      nwh              t t t t t )
  ( MnR          metal1       m1r              t t t t t )
  ( MnR          metal2       m2r              t t t t t )
  ( MnR          metal3       m3r              t t t t t )
  ( MnR          metal4       m4r              t t t t t )
  ( MnR          metal5       m5r              t t t t t )
  ( MnR          metal6       m6r              t t t t t )
  ( MnR          metal7       m7r              t t t t t )
  ( MnR          metal8       m8r              t t t t t )
  ( MnR          topmetal1    tm1r             t t t t t )
  ( MnR          topmetal2    tm2r             t t t t t )
  ( MnSLOTB      metal1       m1slotb          t t t t t )
  ( MnSLOTB      metal2       m2slotb          t t t t t )
  ( MnSLOTB      metal3       m3slotb          t t t t t )
  ( MnSLOTB      metal4       m4slotb          t t t t t )
  ( MnSLOTB      metal5       m5slotb          t t t t t )
  ( MnSLOTB      metal6       m6slotb          t t t t t )
  ( MnSLOTB      metal7       m7slotb          t t t t t )
  ( MnSLOTB      metal8       m8slotb          t t t t t )
  ( MnSLOT       metal1       m1slot           t t t t t )
  ( MnSLOT       metal2       m2slot           t t t t t )
  ( MnSLOT       metal3       m3slot           t t t t t )
  ( MnSLOT       metal4       m4slot           t t t t t )
  ( MnSLOT       metal5       m5slot           t t t t t )
  ( MnSLOT       metal6       m6slot           t t t t t )
  ( MnSLOT       metal7       m7slot           t t t t t )
  ( MnSLOT       metal8       m8slot           t t t t t )
  ( MnSLOT       topmetal1    tm1slot          t t t t t )
  ( MnSLOT       topmetal2    tm2slot          t t t t t )
  ( MIMCKT       drawing      mimckt           t t t t t )
  ( MIMSHD       drawing      mimshd           t t t t t )
  ( INDR         drawing      indr             t t t t t )
  ( GTFUSE       drawing      gtfuse           t t t t t )
  ( EFUSE        drawing      efuse            t t t t t )
  ( CLPDMY       drawing      clpdmy           t t t t t )
  ( DMRES        drawing      dmres            t t t t t )
  ( SURNW        drawing      surnw            t t t t t )
  ( DDNW         drawing      ddnw             t t t t t )
  ( NODMF        drawing      nodmf            t t t t t )
  ( HRPDMY       drawing      hrpdmy           t t t t t )
  ( MIMDMY       drawing      mimdmy           t t t t t )
  ( MOMDMY       drawing      momdmy           t t t t t )
  ( MOMDMY       mk1          mommk1           t t t t t )
  ( MOMDMY       mk2          mommk2           t t t t t )
  ( MOMDMY       mk3          mommk3           t t t t t )
  ( MOMDMY       mk4          mommk4           t t t t t )
  ( MOMDMY       mk5          mommk5           t t t t t )
  ( MOMDMY       mk6          mommk6           t t t t t )
  ( MOMDMY       mk7          mommk7           t t t t t )
  ( MOMDMY       mk8          mommk8           t t t t t )
  ( INDMY        drawing      indmy            t t t t t )
  ( RFDEV        drawing      rfdev            t t t t t )
  ( RFMOSD       drawing      rfmosd           t t t t t )
  ( JVARDUM      drawing      jvardum          t t t t t )
  ( MD           drawing      md               t t t t t )
  ( RF3T         drawing      rf3t             t t t t t )
  ( RP185        drawing      rp185            t t t t t )
  ( CCT          drawing      cct              t t t t t )
  ( PLDMK        drawing      pldmk            t t t t t )
  ( NFDMK        drawing      nfdmk            t t t t t )
  ( SRAM         stsram       stsram           t t t t t )
  ( SRAM         dnsram       dnsram           t t t t t )
  ( SRAM         udsram       udsram           t t t t t )
  ( SRAM         dpsram       dpsram           t t t t t )
  ( SRAM         lrsram       lrsram           t t t t t )
  ( RFSD         drawing      rfsd             t t t t t )
  ( RFDN6T       drawing      rfdn6t           t t t t t )
  ( MIMSTK       drawing      mimstk           t t t t t )
  ( STIDMY       drawing      stidmy           t t t t t )
  ( MARK         markg        markg            t t t t t )
  ( MARK         marks        marks            t t t t t )
  ( MARK         markf        markf            t t t t t )
  ( DUPMK1       drawing      dupmk1           t t t t t )
  ( FUSE         mk1          fusemk1          t t t t t )
  ( ALMK1        drawing      almk1            t t t t t )
  ( background   drawing      background       t nil t nil nil )
  ( grid         drawing      grid             t nil t nil nil )
  ( grid         drawing1     grid1            t nil t nil nil )
  ( annotate     drawing      annotate         t t t t nil )
  ( annotate     drawing1     annotate1        t t t t nil )
  ( annotate     drawing2     annotate2        t t t t nil )
  ( annotate     drawing3     annotate3        t t t t nil )
  ( annotate     drawing4     annotate4        t t t t nil )
  ( annotate     drawing5     annotate5        t t t t nil )
  ( annotate     drawing6     annotate6        t t t t nil )
  ( annotate     drawing7     annotate7        t t t t nil )
  ( annotate     drawing8     annotate8        t t t t nil )
  ( annotate     drawing9     annotate9        t t t t nil )
  ( instance     drawing      instance         t t t t nil )
  ( instance     label        instanceLbl      t t t t nil )
  ( prBoundary   drawing      prBoundary       t t t t nil )
  ( prBoundary   boundary     prBoundaryBnd    t t t t nil )
  ( prBoundary   label        prBoundaryLbl    t t t t nil )
  ( align        drawing      defaultPacket    t t t t nil )
  ( hardFence    drawing      hardFence        t t t t nil )
  ( softFence    drawing      softFence        t t t t nil )
  ( text         drawing      text             t t t t nil )
  ( text         drawing1     text1            t t t t nil )
  ( text         drawing2     text2            t t t t nil )
  ( border       drawing      border           t t t t nil )
  ( device       drawing      device           t t t t nil )
  ( device       label        deviceLbl        t t t t nil )
  ( device       drawing1     device1          t t t t nil )
  ( device       drawing2     device2          t t t t nil )
  ( device       annotate     deviceAnt        t t t t nil )
  ( wire         drawing      wire             t t t t nil )
  ( wire         label        wireLbl          t t t t nil )
  ( wire         flight       wireFlt          t t t t nil )
  ( pin          label        pinLbl           t t t t nil )
  ( pin          drawing      pin              t t t t nil )
  ( pin          annotate     pinAnt           t t t t nil )
  ( axis         drawing      axis             t nil t t nil )
  ( edgeLayer    drawing      edgeLayer        t t t t nil )
  ( edgeLayer    pin          edgeLayerPin     t t t t nil )
  ( snap         drawing      snap             t t t t nil )
  ( stretch      drawing      stretch          t t t t nil )
  ( y0           drawing      y0               t t t t nil )
  ( y1           drawing      y1               t t t t nil )
  ( y2           drawing      y2               t t t t nil )
  ( y3           drawing      y3               t t t t nil )
  ( y4           drawing      y4               t t t t nil )
  ( y5           drawing      y5               t t t t nil )
  ( y6           drawing      y6               t t t t nil )
  ( y7           drawing      y7               t t t t nil )
  ( y8           drawing      y8               t t t t nil )
  ( y9           drawing      y9               t t t t nil )
  ( hilite       drawing      hilite           t t t t nil )
  ( hilite       drawing1     hilite1          t t t t nil )
  ( hilite       drawing2     hilite2          t t t t nil )
  ( hilite       drawing3     hilite3          t t t t nil )
  ( hilite       drawing4     hilite4          t t t t nil )
  ( hilite       drawing5     hilite5          t t t t nil )
  ( hilite       drawing6     hilite6          t t t t nil )
  ( hilite       drawing7     hilite7          t t t t nil )
  ( hilite       drawing8     hilite8          t t t t nil )
  ( hilite       drawing9     hilite9          t t t t nil )
  ( select       drawing      select           t t t t nil )
  ( drive        drawing      drive            t t t t nil )
  ( hiz          drawing      hiz              t t t t nil )
  ( resist       drawing      resist           t t t t nil )
  ( spike        drawing      spike            t t t t nil )
  ( supply       drawing      supply           t t t t nil )
  ( unknown      drawing      unknown          t t t t nil )
  ( unset        drawing      unset            t t t t nil )
  ( designFlow   drawing      designFlow       t nil nil nil nil )
  ( designFlow   drawing1     designFlow1      t nil nil nil nil )
  ( designFlow   drawing2     designFlow2      t nil nil nil nil )
  ( designFlow   drawing3     designFlow3      t nil nil nil nil )
  ( designFlow   drawing4     designFlow4      t nil nil nil nil )
  ( designFlow   drawing5     designFlow5      t nil nil nil nil )
  ( designFlow   drawing6     designFlow6      t nil nil nil nil )
  ( designFlow   drawing7     designFlow7      t nil nil nil nil )
  ( designFlow   drawing8     designFlow8      t nil nil nil nil )
  ( designFlow   drawing9     designFlow9      t nil nil nil nil )
  ( changedLayer tool0        changedLayerTl0  nil nil t nil nil )
  ( changedLayer tool1        changedLayerTl1  nil nil t nil nil )
  ( marker       warning      markerWarn       t t t t nil )
  ( marker       error        markerErr        t t t t nil )
  ( Row          drawing      Row              t t t t nil )
  ( Row          label        RowLbl           t t t t nil )
  ( Group        drawing      Group            t t t t nil )
  ( Group        label        GroupLbl         t t t t nil )
  ( Cannotoccupy drawing      Cannotoccupy     t t t t nil )
  ( Cannotoccupy boundary     CannotoccupyBnd  t t t t nil )
  ( Canplace     drawing      Canplace         t t t t nil )
  ( Unrouted     drawing      Unrouted         t t t t nil )
  ( Unrouted     drawing1     Unrouted1        t t t t nil )
  ( Unrouted     drawing2     Unrouted2        t t t t nil )
  ( Unrouted     drawing3     Unrouted3        t t t t nil )
  ( Unrouted     drawing4     Unrouted4        t t t t nil )
  ( Unrouted     drawing5     Unrouted5        t t t t nil )
  ( Unrouted     drawing6     Unrouted6        t t t t nil )
  ( Unrouted     drawing7     Unrouted7        t t t t nil )
  ( Unrouted     drawing8     Unrouted8        t t t t nil )
  ( Unrouted     drawing9     Unrouted9        t t t t nil )
  ( snap         boundary     snap             t t t t nil )
 ) ;techDisplays

) ;layerDefinitions


;********************************
; LAYER RULES
;********************************
layerRules(

 functions(
 ;( layer                       function        [maskNumber])
 ;( -----                       --------        ------------)
  ( PSUB                     	"pwell"     	1            )
  ( DNW                      	"pwell"     	2            )
  ( NW                       	"nwell"     	3            )
  ( AA                       	"diff"      	4            )
  ( GT                       	"poly"      	5            )
  ( SN                       	"nplus"     	13           )
  ( SP                       	"pplus"     	19           )
  ( SAB                      	"recognition"	20           )
  ( CT                       	"cut"       	21           )
  ( M1                       	"metal"     	22           )
  ( V1                       	"cut"       	23           )
  ( M2                       	"metal"     	24           )
  ( V2                       	"cut"       	25           )
  ( M3                       	"metal"     	26           )
  ( V3                       	"cut"       	27           )
  ( M4                       	"metal"     	28           )
  ( V4                       	"cut"       	29           )
  ( M5                       	"metal"     	30           )
  ( V5                       	"cut"       	31           )
  ( M6                       	"metal"     	32           )
  ( V6                       	"cut"       	33           )
  ( M7                       	"metal"     	34           )
  ( V7                       	"cut"       	35           )
  ( M8                       	"metal"     	36           )
  ( PA                       	"cut"       	41           )
  ( ALPA                     	"metal"     	42           )
 ) ;functions

) ;layerRules


;********************************
; VIADEFS
;********************************
viaDefs(

 standardViaDefs(
 ;( viaDefName	layer1	layer2	(cutLayer cutWidth cutHeight [resistancePerCut]) 
 ;   (cutRows	cutCol	(cutSpace)) 
 ;   (layer1Enc) (layer2Enc)	(layer1Offset)	(layer2Offset)	(origOffset) 
 ;   [implant1	 (implant1Enc)	[implant2	(implant2Enc) [well/substrate]]]) 
 ;( -------------------------------------------------------------------------- ) 
  ( M1_SUB      	AA          M1          	("CT" 0.16 0.16)
     (1 1 (0.18 0.18))
     (0.05 0.05)	(0.0 0.05)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     SP          	(0.03 0.03)
  )
  ( M1_NW       	AA          M1          	("CT" 0.16 0.16)
     (1 1 (0.18 0.18))
     (0.05 0.05)	(0.0 0.05)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     SN          	(0.03 0.03)	NW          	(0.28 0.23)
  )
  ( M1_SP       	AA          M1          	("CT" 0.16 0.16)
     (1 1 (0.18 0.18))
     (0.05 0.05)	(0.0 0.05)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     SP          	(0.03 0.03)
  )
  ( M1_SN       	AA          M1          	("CT" 0.16 0.16)
     (1 1 (0.18 0.18))
     (0.05 0.05)	(0.0 0.05)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     SN          	(0.03 0.03)
  )
  ( M1_AA       	AA          M1          	("CT" 0.16 0.16)
     (1 1 (0.18 0.18))
     (0.05 0.05)	(0.0 0.05)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M1_GT       	GT          M1          	("CT" 0.16 0.16)
     (1 1 (0.18 0.18))
     (0.06 0.06)	(0.0 0.05)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M2_M1       	M1          M2          	("V1" 0.19 0.19)
     (1 1 (0.21 0.21))
     (0.005 0.05)	(0.005 0.05)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M3_M2       	M2          M3          	("V2" 0.19 0.19)
     (1 1 (0.21 0.21))
     (0.005 0.05)	(0.005 0.05)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M4_M3       	M3          M4          	("V3" 0.19 0.19)
     (1 1 (0.21 0.21))
     (0.005 0.05)	(0.005 0.05)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M5_M4       	M4          M5          	("V4" 0.19 0.19)
     (1 1 (0.21 0.21))
     (0.005 0.05)	(0.005 0.05)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M6_M5       	M5          M6          	("V5" 0.19 0.19)
     (1 1 (0.21 0.21))
     (0.005 0.05)	(0.005 0.05)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M7_M6       	M6          M7          	("V6" 0.36 0.36)
     (1 1 (0.34 0.34))
     (0.01 0.05)	(0.03 0.07) 	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M8_M7       	M7          M8          	("V7" 0.36 0.36)
     (1 1 (0.34 0.34))
     (0.01 0.05)	(0.30 0.42) 	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( ALPA_M8     	M8          ALPA        	("PA" 4.0 4.0)
     (1 1 (4.0 4.0))
     (1.5 1.5)	    (1.5 1.5)	    (0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
 ) ;standardViaDefs

) ;viaDefs



;********************************
; CONSTRAINT GROUPS
;********************************
constraintGroups(

 ;( group	[override] )
 ;( -----	---------- )
  ( "virtuosoDefaultExtractorSetup"	nil

    interconnect(
     ( validLayers   (NW  AA  GT  CT  M1  V1  M2  V2  M3  V3  M4  V4  M5  V5  M6  V6  M7  V7  M8  PA  ALPA  ) )
     ( validVias     (M1_GT  M1_NW  M1_SUB  M1_SN  M1_SP  M1_AA  M2_M1  M3_M2  M4_M3  M5_M4  M6_M5  M7_M6  M8_M7  ALPA_M8  ) )
    ) ;interconnect
  ) ;virtuosoDefaultExtractorSetup

 ;( group	[override] )
 ;( -----	---------- )
  ( "virtuosoDefaultTaper"	nil    "taper"

    interconnect(
     ( validLayers   (GT  M1  ) )
     ( validVias     (M1_GT  ) )
    ) ;interconnect

    spacings(
     ( taperHalo                  0.0 )
    ) ;spacings
  ) ;virtuosoDefaultTaper

 ;( group	[override] )
 ;( -----	---------- )
  ( "virtuosoDefaultSetup"	nil

    interconnect(
     ( validLayers   (M1  M2  M3  M4  M5  M6  M7  M8  ALPA  ) )
     ( validVias     (M1_GT  M2_M1  M3_M2  M4_M3  M5_M4  M6_M5  M7_M6  M8_M7  ALPA_M8  ) )
    ) ;interconnect
  ) ;virtuosoDefaultSetup

 ;( group	[override] )
 ;( -----	---------- )
  ( "foundry"	nil

    spacings(

     ( minWidth                     "AA"	0.15 )
    ;( maxWidth                     "AA"	     )
     ( minArea                      "AA"	0.10 )
     ( minWidth                     "M1"	0.16 )
     ( maxWidth                     "M1"	14.0 )
     ( minArea                      "M1"	0.08 )
     ( minWidth                     "M2"	0.20 )
     ( maxWidth                     "M2"	15.0 )
     ( minArea                      "M2"	0.12 )
     ( minWidth                     "M3"	0.20 )
     ( maxWidth                     "M3"	15.0 )
     ( minArea                      "M3"	0.12 )
     ( minWidth                     "M4"	0.20 )
     ( maxWidth                     "M4"	15.0 )
     ( minArea                      "M4"	0.12 )
     ( minWidth                     "M5"	0.20 )
     ( maxWidth                     "M5"	15.0 )
     ( minArea                      "M5"	0.12 )
     ( minWidth                     "M6"	0.20 )
     ( maxWidth                     "M6"	15.0 )
     ( minArea                      "M6"	0.12 )
     ( minWidth                     "M7"	0.42 'ref  "TM.1" );;
     ( maxWidth                     "M7"	30.0 );;
     ( minArea                      "M7"	0.42 'ref  "TM.5" );;
     ( minWidth                     "M8"	1.50 'ref  "MTT.1" );;
     ( maxWidth                     "M8"	30.0 );;
     ( minArea                      "M8"	2.25 'ref  "MTT.6" );;
     ( minWidth                     "ALPA"	3.00 )

     ( minWidth                     "CT"	0.16 )
     ( maxWidth                     "CT"	0.16 )
     ( minSpacing                   "CT"	0.18 )
     ( minDiffNetSpacing            "CT"	0.18 )
    ;( minLargeViaArrayCutSpacing   "CT"	0.18  'ref  "CT.2" )
    ;( minLargeViaArrayWidth        "CT"	1.40 )
     ( minWidth                     "V1"	0.19 )
     ( maxWidth                     "V1"	0.19 )
     ( minSpacing                   "V1"	0.21 )
     ( minDiffNetSpacing            "V1"	0.21 )
     ( minLargeViaArrayCutSpacing   "V1"	0.25  'ref  "V1.2" )
     ( minLargeViaArrayWidth        "V1"	1.40 )
     ( minWidth                     "V2"	0.19 )
     ( maxWidth                     "V2"	0.19 )
     ( minSpacing                   "V2"	0.21 )
     ( minDiffNetSpacing            "V2"	0.21 )
     ( minLargeViaArrayCutSpacing   "V2"	0.25  'ref  "Vn.2" )
     ( minLargeViaArrayWidth        "V2"	1.40 )
     ( minWidth                     "V3"	0.19 )
     ( maxWidth                     "V3"    0.19 )
     ( minSpacing                   "V3"	0.21 )
     ( minDiffNetSpacing            "V3"	0.21 )
     ( minLargeViaArrayCutSpacing   "V3"	0.25  'ref  "Vn.2" )
     ( minLargeViaArrayWidth        "V3"	1.40 )
     ( minWidth                     "V4"	0.19 )
     ( maxWidth                     "V4"	0.19 )
     ( minSpacing                   "V4"	0.21 )
     ( minDiffNetSpacing            "V4"	0.21 )
     ( minLargeViaArrayCutSpacing   "V4"	0.25  'ref  "Vn.2" )
     ( minLargeViaArrayWidth        "V4"	1.40 )
     ( minWidth                     "V5"	0.19 )
     ( maxWidth                     "V5"	0.19 )
     ( minSpacing                   "V5"	0.21 )
     ( minDiffNetSpacing            "V5"	0.21 )
     ( minLargeViaArrayCutSpacing   "V5"	0.25  'ref  "Vn.2" )
     ( minLargeViaArrayWidth        "V5"	1.40 )
     ( minWidth                     "V6"	0.36 );;
     ( maxWidth                     "V6"	0.36 );;
     ( minSpacing                   "V6"	0.34 );;
     ( minDiffNetSpacing            "V6"	0.34 );;
     ( minLargeViaArrayCutSpacing   "V6"	0.50  'ref  "TV.2" );;
     ( minLargeViaArrayWidth        "V6"	1.78 );;
     ( minWidth                     "V7"	0.36 );;
     ( maxWidth                     "V7"	0.36 );;
     ( minSpacing                   "V7"	0.34 );;
     ( minDiffNetSpacing            "V7"	0.34 );;
     ( minLargeViaArrayCutSpacing   "V7"	0.50  'ref  "TV.2" );;
     ( minLargeViaArrayWidth        "V7"	1.78 );;

     ( minWidth                     "PA"	4.0 )
    ;( maxWidth                     "PA"	7.0 )
     ( minSpacing                   "PA"	4.0 )
     ( minDiffNetSpacing            "PA"	4.0 )
     ( minLargeViaArrayCutSpacing   "PA"	7.0  'ref  "PA.2" )
     ( minLargeViaArrayWidth        "PA"	10 )
    );spacings

    orderedSpacings(
     ( minExtensionDistance         "AA"	"CT"		0.06 )
     ( minExtensionDistance         "GT"	"CT"		0.06 )
     ( minExtensionDistance         "M1"	"CT"		0.00 )
     ( minExtensionDistance         "M1"	"V1"		0.005 )
     ( minExtensionDistance         "M2"	"V1"		0.005 )
     ( minExtensionDistance         "M2"	"V2"		0.005 )
     ( minExtensionDistance         "M3"	"V2"		0.005 )
     ( minExtensionDistance         "M3"	"V3"		0.005 )
     ( minExtensionDistance         "M4"	"V3"		0.005 )
     ( minExtensionDistance         "M4"	"V4"		0.005 )
     ( minExtensionDistance         "M5"	"V4"		0.005 )
     ( minExtensionDistance         "M5"	"V5"		0.005 )
     ( minExtensionDistance         "M6"	"V5"		0.005 )
     ( minExtensionDistance         "M6"	"V6"		0.01 );;
     ( minExtensionDistance         "M7"	"V6"		0.03 );;
     ( minExtensionDistance         "M7"	"V7"		0.01 );;
     ( minExtensionDistance         "M8"	"V7"		0.30 );;
     ( minExtensionDistance         "M8"	"PA"		1.50 );;
     ( minExtensionDistance         "ALPA"  "PA"		1.50 )
     ( minOppExtension              "AA"	"CT"		(0.06  0.06)   'ref  "CT.5" )
     ( minOppExtension              "GT"	"CT"		(0.06  0.06)   'ref  "CT.6" )
     ( minOppExtension              "M1"	"CT"		(0.00  0.05)   'ref  "CT.7 CT.8" )
     ( minOppExtension              "M1"	"V1"		(0.05  0.005)  'ref  "V1.5 V1.4" )
     ( minOppExtension              "M2"	"V1"		(0.005 0.03)   'ref  "V1.6 V1.7" )
     ( minOppExtension              "M2"	"V2"		(0.05  0.005)  'ref  "Vn.4 Vn.3" )
     ( minOppExtension              "M3"	"V2"		(0.005 0.03)   'ref  "Vn.5 Vn.6" )
     ( minOppExtension              "M3"	"V3"		(0.05  0.005)  'ref  "Vn.4 Vn.3" )
     ( minOppExtension              "M4"	"V3"		(0.005 0.03)   'ref  "Vn.5 Vn.6" )
     ( minOppExtension              "M4"	"V4"		(0.05  0.005)  'ref  "Vn.4 Vn.3" )
     ( minOppExtension              "M5"	"V4"		(0.005 0.03)   'ref  "Vn.5 Vn.6" )
     ( minOppExtension              "M5"	"V5"		(0.05  0.005)  'ref  "Vn.4 Vn.3" )
     ( minOppExtension              "M6"	"V5"		(0.005 0.03)   'ref  "Vn.5 Vn.6" )
     ( minOppExtension              "M6"	"V6"		(0.05  0.01)   'ref  "TV.5 TV.4" );;
     ( minOppExtension              "M7"	"V6"		(0.03  0.07)   'ref  "TV.6 TV.7" );;
     ( minOppExtension              "M7"	"V7"		(0.05  0.01)   'ref  "TV.5 TV.4" );;
     ( minOppExtension              "M8"	"V7"		(0.42  0.30)   'ref  "MTT.4 MTT.3" );;
     ( minOppExtension              "M8"	"PA"		(1.50  1.50)   'ref  "PA.4 PA.4" );;
     ( minOppExtension            "ALPA"	"PA"		(1.50  1.50)   'ref  "PA.3 PA.3" )
    );orderedSpacings
  );foundry
);constraintGroups

;********************************
; DEVICES
;********************************
devices(
tcCreateCDSDeviceClass()


multipartPathTemplates(
; ( name [masterPath] [offsetSubpaths] [encSubPaths] [subRects] )
; 
;   masterPath:
;   (layer [width] [choppable] [endType] [beginExt] [endExt] [justify] [offset]
;   [connectivity])
; 
;   offsetSubpaths:
;   (layer [width] [choppable] [separation] [justification] [begOffset] [endOffset]
;   [connectivity])
; 
;   encSubPaths:
;   (layer [enclosure] [choppable] [separation] [begOffset] [endOffset]
;   [connectivity])
; 
;   subRects:
;   (layer [width] [length] [choppable] [separation] [justification] [space] [begOffset] [endOffset] [gap] 
;   [connectivity] [beginSegOffset] [endSegOffset])
; 
;   connectivity:
;   ([I/O type] [pin] [accDir] [dispPinName] [height] [ layer]
;    [layer] [justification] [font] [textOptions] [orientation]
;    [refHandle] [offset])
; 
; ( --------------------------------------------------------------------- )
  (NGR 
    (("AA" "drawing")	(0.22 + (2 * 0.01) + 0.02)	t)
    ((("M1" "drawing")	(0.23 + (2 * 0.015))	t	0         	center	(- (0.01 - 0.0))	
     (minus	(0.01 - 0.0)	))
     (("NW" "drawing")	0.72	t	0         	center	0.23	0.23)
    )
    ((("SN" "drawing")	-0.03	t)
    )
    ((("CT" "drawing")	0.16	0.16	t	0         	center	0.18	(-0.18 / 2)	(-0.18 / 2)	distribute)
    )
  )
  (PGR 
    (("AA" "drawing")	(0.22 + (2 * 0.01) + 0.02)	t)
    ((("M1" "drawing")	(0.23 + (2 * 0.015))	t	0         	center	(- (0.01 - 0.0))	
     (minus	(0.01 - 0.0)	))
    )
    ((("SP" "drawing")	-0.03	t)
    )
    ((("CT" "drawing")	0.16	0.16	t	0         	center	0.18	(-0.18 / 2)	(-0.18 / 2)	distribute)
    )
  )
)  ;multipartPathTemplates

) ;devices
