
;CSMC 0.153u c1513
;IC6 technology file
;generated by GTE Version: 03.05.002  Build: @1650 (20130917032931) on Jan 14, 2020
;parameter file: /sto/stosh1/work/LIB/018_MCU/personal/zhouc/pdk_zhouc_0153shrink/pdk_pcell/20191125/param_5v/c1813_techSelect_M6_12K_5v.param
;topMetal_All false
;topMetal_M2 false
;topMetal_M3 false
;topMetal_M4 false
;topMetal_M5 false
;topMetal_M6 true
;Thickness_8K false
;Thickness_12K true
;Thickness_25K false
;Thickness_35K false

controls(

 mfgGridResolution(
      ( 0.001000 )
 ) ;mfgGridResolution

) ;controls


layerDefinitions(

    techLayers(
;       ( LayerName       Layer#          Abbreviation     )
;       ( ---------       ------          ------------     )
        ( TB              1               TB               )
        ( TO              2               TO               )
        ( GT              3               GT               )
        ( SP              4               SP               )
        ( SN              5               SN               )
        ( W1              6               W1               )
        ( A1              7               A1               )
        ( W2              8               W2               )
        ( A2              9               A2               )
        ( CP              10              CP               )
        ( PT              11              PT               )
        ( IM              13              IM               )
        ( PC              14              PC               )
        ( NLDD            15              NLDD             )
        ( LR              16              LR               )
        ( HV              17              HV               )
        ( HN              18              HN               )
        ( HP              19              HP               )
        ( BN              20              BN               )
        ( RO              23              RO               )
        ( MP              24              MP               )
        ( SI              25              SI               )
        ( NG              26              NG               )
        ( LN              29              LN               )
        ( LP              30              LP               )
        ( PWB             31              PWB              )
        ( HR              33              HR               )
        ( PI              34              PI               )
        ( W3              40              W3               )
        ( A3              41              A3               )
        ( PD              44              PD               )
        ( MN              45              MN               )
        ( SE              46              SE               )
        ( DN              55              DN               )
        ( SCRIBE          60              SCRIBE           )
        ( W4              61              W4               )
        ( A4              62              A4               )
        ( IPTAG           63              IPTAG            )
        ( NM              70              NM               )
        ( HF              73              HF               )
        ( NX              76              NX               )
        ( PX              77              PX               )
        ( MCT             78              MCT              )
        ( FU              81              FU               )
        ( MTT             86              MTT              )
        ( PB              89              PB               )
        ( W5              91              W5               )
        ( A5              92              A5               )
        ( WT              93              WT               )
        ( AT              94              AT               )
        ( SEALRING        100             SEALRING         )
        ( LMARK           101             LMARK            )
        ( LOGO            103             LOGO             )
        ( MIS             104             MIS              )
        ( VARMARK         105             VARMARK          )
        ( RES_HR1K        107             RES_HR1K         )
        ( RES_HR2K        108             RES_HR2K         )
        ( RES_FUSE        109             RES_FUSE         )
        ( DCTY            110             DCTY             )
        ( EXT_SUB         111             EXT_SUB          )
        ( RES_NW          112             RES_NW           )
        ( DIODE           113             DIODE            )
        ( CAP             114             CAP              )
        ( BJT             115             BJT              )
        ( RFDUM           116             RFDUM            )
        ( INDUM           117             INDUM            )
        ( EXCLU           118             EXCLU            )
        ( SGND            119             SGND             )
        ( RES_MET         120             RES_MET          )
        ( A1TEXT          121             A1TEXT           )
        ( A2TEXT          122             A2TEXT           )
        ( A3TEXT          123             A3TEXT           )
        ( A4TEXT          124             A4TEXT           )
        ( A5TEXT          125             A5TEXT           )
        ( ATTEXT          126             ATTEXT           )
        ( MTTSLOT         130             MTTSLOT          )
        ( ATSLOT          133             ATSLOT           )
        ( A5SLOT          134             A5SLOT           )
        ( A4SLOT          135             A4SLOT           )
        ( A1SLOT          136             A1SLOT           )
        ( A2SLOT          137             A2SLOT           )
        ( A3SLOT          138             A3SLOT           )
        ( IPB             147             IPB              )
        ( TODUM           148             TODUM            )
        ( GTDUM           149             GTDUM            )
        ( PSUB2           150             PSUB2            )
        ( MCTM5           151             MCTM5            )
        ( MCTM4           152             MCTM4            )
        ( MCTM3           153             MCTM3            )
        ( MCTM2           154             MCTM2            )
        ( RNDMY           155             RNDMY            )
        ( RPDMY           156             RPDMY            )
        ( DUMBM           157             DUMBM            )
        ( DUMBP           158             DUMBP            )
        ( DUMBA           159             DUMBA            )
        ( NODMF           160             NODMF            )
        ( RES_TO          161             RES_TO           )
        ( RES_PY          162             RES_PY           )
        ( RES_M1          163             RES_M1           )
        ( RES_M2          164             RES_M2           )
        ( RES_M3          165             RES_M3           )
        ( RES_M4          166             RES_M4           )
        ( RES_M5          167             RES_M5           )
        ( RES_MT          168             RES_MT           )
        ( RES_HR          169             RES_HR           )
        ( A1DUM           170             A1DUM            )
        ( A2DUM           171             A2DUM            )
        ( A3DUM           172             A3DUM            )
        ( A4DUM           173             A4DUM            )
        ( A5DUM           174             A5DUM            )
        ( ATDUM           175             ATDUM            )
        ( MTTDUM          176             MTTDUM           )
        ( VARJUN          179             VARJUN           )
        ( ESD             180             ESD              )
        ( OPCBLK          181             OPCBLK           )
        ( VTSRAM          182             VTSRAM           )
        ( NOBIAS          183             NOBIAS           )
        ( ESD2            184             ESD2             )
        ( MOM             185             MOM              )
        ( MT              186             MT               )
    ) ;techLayers

    techPurposes(
;       ( PurposeName     Purpose#        Abbreviation     )
;       ( ---------       ------          ------------     )
        ( mark            1               mark             )
        ( dumy            2               dumy             )
        ( g2              6               g2               )
        ( g3              7               g3               )
        ( m2              15              m2               )
        ( txt             20              txt              )
        ( DB              30              DB               )
        ( tag             63              tag              )
        ( drw             64              drw              )
        ( ter             65              ter              )
        ( iso             66              iso              )
    ) ;techPurposes

    techLayerPurposePriorities(
;       ( LayerName       Purpose          )
;       ( ---------       -------          )
        ( DN              drawing          )
        ( DN              mark             )
        ( TB              drawing          )
        ( NX              drawing          )
        ( TO              drawing          )
        ( SP              drawing          )
        ( SN              drawing          )
        ( GT              drawing          )
        ( CP              drawing          )
        ( PT              drawing          )
        ( PX              drawing          )
        ( NLDD            drawing          )
        ( PC              drawing          )
        ( LR              drawing          )
        ( HP              drawing          )
        ( BN              drawing          )
        ( HV              drawing          )
        ( SE              drawing          )
        ( SI              drawing          )
        ( HN              drawing          )
        ( RO              drawing          )
        ( IM              drawing          )
        ( LN              drawing          )
        ( LP              drawing          )
        ( IPTAG           tag              )
        ( PB              drawing          )
        ( NG              drawing          )
        ( FU              drawing          )
        ( NM              drawing          )
        ( HR              drawing          )
        ( HF              drawing          )
        ( PWB             drawing          )
        ( PD              drawing          )
        ( PI              drawing          )
        ( MP              drawing          )
        ( MN              drawing          )
        ( W1              drawing          )
        ( A1              drawing          )
        ( W2              drawing          )
        ( A2              drawing          )
        ( W3              drawing          )
        ( A3              drawing          )
        ( W4              drawing          )
        ( A4              drawing          )
        ( W5              drawing          )
        ( A5              drawing          )
        ( WT              drawing          )
        ( AT              drawing          )
        ( MCT             drawing          )
        ( MT              drw              )
        ( MTT             drawing          )
        ( SCRIBE          drawing          )
        ( LMARK           drawing          )
        ( LOGO            drawing          )
        ( LOGO            txt              )
        ( SEALRING        drawing          )
        ( MCT             m2               )
        ( A1TEXT          drawing          )
        ( A2TEXT          drawing          )
        ( A3TEXT          drawing          )
        ( A4TEXT          drawing          )
        ( A5TEXT          drawing          )
        ( ATTEXT          drawing          )
        ( PT              txt              )
        ( TB              txt              )
        ( A1SLOT          slot             )
        ( A2SLOT          slot             )
        ( A3SLOT          slot             )
        ( A4SLOT          slot             )
        ( A5SLOT          slot             )
        ( ATSLOT          slot             )
        ( MTTSLOT         slot             )
        ( PSUB2           mark             )
        ( MCTM5           mark             )
        ( MCTM4           mark             )
        ( MCTM3           mark             )
        ( MCTM2           mark             )
        ( VARJUN          mark             )
        ( VARMARK         mark             )
        ( ESD             mark             )
        ( DCTY            mark             )
        ( MIS             mark             )
        ( IPB             mark             )
        ( RES_TO          mark             )
        ( RES_PY          mark             )
        ( ESD2            mark             )
        ( RES_M1          mark             )
        ( RES_M2          mark             )
        ( RES_M3          mark             )
        ( RES_M4          mark             )
        ( RES_M5          mark             )
        ( RES_MT          mark             )
        ( RES_HR1K        mark             )
        ( RES_HR2K        mark             )
        ( RES_FUSE        mark             )
        ( EXT_SUB         mark             )
        ( RES_HR          mark             )
        ( TO              net              )
        ( RES_NW          mark             )
        ( RES_MET         mark             )
        ( RNDMY           mark             )
        ( RPDMY           mark             )
        ( DIODE           mark             )
        ( DIODE           iso              )
        ( CAP             mark             )
        ( MOM             mark             )
        ( MOM             ter              )
        ( BJT             mark             )
        ( RFDUM           g2               )
        ( RFDUM           mark             )
        ( INDUM           mark             )
        ( EXCLU           mark             )
        ( NOBIAS          mark             )
        ( SGND            mark             )
        ( DUMBM           mark             )
        ( DUMBP           mark             )
        ( DUMBA           mark             )
        ( NODMF           mark             )
        ( OPCBLK          mark             )
        ( VTSRAM          mark             )
        ( A1DUM           dumy             )
        ( A2DUM           dumy             )
        ( A3DUM           dumy             )
        ( A4DUM           dumy             )
        ( A5DUM           dumy             )
        ( ATDUM           dumy             )
        ( MTTDUM          dumy             )
        ( TODUM           dumy             )
        ( GTDUM           dumy             )
        ( A1DUM           DB               )
        ( A2DUM           DB               )
        ( A3DUM           DB               )
        ( A4DUM           DB               )
        ( A5DUM           DB               )
        ( ATDUM           DB               )
        ( MTTDUM          DB               )
        ( VTSRAM          g2               )
        ( VTSRAM          g3               )
        ( TB              net              )
        ( MCT             net              )
        ( DN              net              )
        ( GT              label            )
        ( GT              pin              )
        ( GT              boundary         )
        ( GT              net              )
        ( A1              label            )
        ( A1              pin              )
        ( A1              boundary         )
        ( A1              net              )
        ( A2              label            )
        ( A2              pin              )
        ( A2              boundary         )
        ( A2              net              )
        ( A3              label            )
        ( A3              pin              )
        ( A3              boundary         )
        ( A3              net              )
        ( A4              label            )
        ( A4              pin              )
        ( A4              boundary         )
        ( A4              net              )
        ( A5              label            )
        ( A5              pin              )
        ( A5              boundary         )
        ( A5              net              )
        ( AT              label            )
        ( AT              pin              )
        ( AT              boundary         )
        ( AT              net              )
        ( MTT             label            )
        ( MTT             pin              )
        ( MTT             boundary         )
        ( MTT             net              )
        ( W1              net              )
        ( W1              pin              )
        ( W1              boundary         )
        ( W2              net              )
        ( W2              pin              )
        ( W2              boundary         )
        ( W3              net              )
        ( W3              pin              )
        ( W3              boundary         )
        ( W4              net              )
        ( W4              pin              )
        ( W4              boundary         )
        ( W5              net              )
        ( W5              pin              )
        ( W5              boundary         )
        ( WT              net              )
        ( WT              pin              )
        ( WT              boundary         )
    ) ;techLayerPurposePriorities

    techDisplays(
;       ( LayerName       Purpose         Packet                          Vis Sel Chg Drg Valid )
;       ( ---------       -------         ------                          --- --- --- --- ----- )
        ( DN              drawing         DN                              t   t   t   t   t     )
        ( DN              mark            DN_mark                         t   t   t   t   t     )
        ( TB              drawing         TB                              t   t   t   t   t     )
        ( NX              drawing         NX                              t   t   t   t   t     )
        ( TO              drawing         annotate2                       t   t   t   t   t     )
        ( SP              drawing         SP                              t   t   t   t   t     )
        ( SN              drawing         SN                              t   t   t   t   t     )
        ( GT              drawing         GT                              t   t   t   t   t     )
        ( CP              drawing         CP                              t   t   t   t   t     )
        ( PT              drawing         annotate7                       t   t   t   t   t     )
        ( PX              drawing         designFlow9                     t   t   t   t   t     )
        ( NLDD            drawing         NLDD                            t   t   t   t   t     )
        ( PC              drawing         PC                              t   t   t   t   nil   )
        ( LR              drawing         LR                              t   t   t   t   t     )
        ( HP              drawing         HP                              t   t   t   t   t     )
        ( BN              drawing         BN                              t   t   t   t   t     )
        ( HV              drawing         HV                              t   t   t   t   t     )
        ( SE              drawing         annotate16                      t   t   t   t   t     )
        ( SI              drawing         SI                              t   t   t   t   t     )
        ( HN              drawing         HN                              t   t   t   t   t     )
        ( RO              drawing         RO                              t   t   t   t   t     )
        ( IM              drawing         IM                              t   t   t   t   t     )
        ( LN              drawing         LN                              t   t   t   t   t     )
        ( LP              drawing         LP                              t   t   t   t   t     )
        ( IPTAG           tag             IPTAG_tag                       t   t   t   t   t     )
        ( PB              drawing         PB                              t   t   t   t   t     )
        ( NG              drawing         NG                              t   t   t   t   t     )
        ( FU              drawing         FU                              t   t   t   t   t     )
        ( NM              drawing         NM                              t   t   t   t   t     )
        ( HR              drawing         HR                              t   t   t   t   t     )
        ( HF              drawing         HF                              t   t   t   t   t     )
        ( PWB             drawing         annotate24                      t   t   t   t   t     )
        ( PD              drawing         designFlow                      t   t   t   t   t     )
        ( PI              drawing         designFlow4                     t   t   t   t   t     )
        ( MP              drawing         MP                              t   t   t   t   t     )
        ( MN              drawing         MN                              t   t   t   t   t     )
        ( W1              drawing         W1                              t   t   t   t   t     )
        ( A1              drawing         A1                              t   t   t   t   t     )
        ( W2              drawing         W2                              t   t   t   t   t     )
        ( A2              drawing         A2                              t   t   t   t   t     )
        ( W3              drawing         W3                              t   t   t   t   t     )
        ( A3              drawing         A3                              t   t   t   t   t     )
        ( W4              drawing         W4                              t   t   t   t   t     )
        ( A4              drawing         A4                              t   t   t   t   t     )
        ( W5              drawing         W5                              t   t   t   t   t     )
        ( A5              drawing         A5                              t   t   t   t   t     )
        ( WT              drawing         WT                              t   t   t   t   t     )
        ( AT              drawing         AT                              t   t   t   t   t     )
        ( MCT             drawing         MCT                             t   t   t   t   t     )
        ( MT              drw             MT_drw                          t   t   t   t   t     )
        ( MTT             drawing         MTT                             t   t   t   t   t     )
        ( SCRIBE          drawing         Unrouted2                       t   t   t   t   t     )
        ( LMARK           drawing         LMARK                           t   t   t   t   t     )
        ( LOGO            drawing         LOGO                            t   t   t   t   t     )
        ( LOGO            txt             LOGO_txt                        t   t   t   t   t     )
        ( SEALRING        drawing         Unrouted2                       t   t   t   t   t     )
        ( MCT             m2              MCT_m2                          t   t   t   t   t     )
        ( A1TEXT          drawing         A1TEXT                          t   t   t   t   t     )
        ( A2TEXT          drawing         A2TEXT                          t   t   t   t   t     )
        ( A3TEXT          drawing         A3TEXT                          t   t   t   t   t     )
        ( A4TEXT          drawing         A4TEXT                          t   t   t   t   t     )
        ( A5TEXT          drawing         y4                              t   t   t   t   t     )
        ( ATTEXT          drawing         y5                              t   t   t   t   t     )
        ( PT              txt             PT_txt                          t   t   t   t   t     )
        ( TB              txt             TB_txt                          t   t   t   t   t     )
        ( A1SLOT          slot            A1SLOT                          t   t   t   t   t     )
        ( A2SLOT          slot            A2SLOT                          t   t   t   t   t     )
        ( A3SLOT          slot            A3SLOT                          t   t   t   t   t     )
        ( A4SLOT          slot            A4SLOT                          t   t   t   t   t     )
        ( A5SLOT          slot            y6                              t   t   t   t   t     )
        ( ATSLOT          slot            y7                              t   t   t   t   t     )
        ( MTTSLOT         slot            y8                              t   t   t   t   t     )
        ( PSUB2           mark            PSUB2_mark                      t   t   t   t   t     )
        ( MCTM5           mark            MCTM5_mark                      t   t   t   t   t     )
        ( MCTM4           mark            MCTM4_mark                      t   t   t   t   t     )
        ( MCTM3           mark            MCTM3_mark                      t   t   t   t   t     )
        ( MCTM2           mark            MCTM2_mark                      t   t   t   t   t     )
        ( VARJUN          mark            Unrouted6                       t   t   t   t   t     )
        ( VARMARK         mark            Unrouted6                       t   t   t   t   t     )
        ( ESD             mark            ESD_mark                        t   t   t   t   t     )
        ( DCTY            mark            Unrouted7                       t   t   t   t   t     )
        ( MIS             mark            MIS_mark                        t   t   t   t   t     )
        ( IPB             mark            IPB_mark                        t   t   t   t   t     )
        ( RES_TO          mark            RES_TO_mark                     t   t   t   t   t     )
        ( RES_PY          mark            RES_PY_mark                     t   t   t   t   t     )
        ( ESD2            mark            ESD2_mark                       t   t   t   t   t     )
        ( RES_M1          mark            RES_M1_mark                     t   t   t   t   t     )
        ( RES_M2          mark            RES_M2_mark                     t   t   t   t   t     )
        ( RES_M3          mark            RES_M3_mark                     t   t   t   t   t     )
        ( RES_M4          mark            RES_M4_mark                     t   t   t   t   t     )
        ( RES_M5          mark            RES_M5_mark                     t   t   t   t   t     )
        ( RES_MT          mark            RES_MT_mark                     t   t   t   t   t     )
        ( RES_HR1K        mark            RES_HR1K_mark                   t   t   t   t   t     )
        ( RES_HR2K        mark            RES_HR2K_mark                   t   t   t   t   t     )
        ( RES_FUSE        mark            RES_FUSE_mark                   t   t   t   t   t     )
        ( EXT_SUB         mark            EXT_SUB_mark                    t   t   t   t   t     )
        ( RES_HR          mark            RES_HR_mark                     t   t   t   t   t     )
        ( TO              net             tonet                           t   t   t   t   t     )
        ( RES_NW          mark            RES_NW_mark                     t   t   t   t   t     )
        ( RES_MET         mark            RES_MET_mark                    t   t   t   t   t     )
        ( RNDMY           mark            RNDMY_mark                      t   t   t   t   t     )
        ( RPDMY           mark            Unrouted                        t   t   t   t   t     )
        ( DIODE           mark            DIODE_mark                      t   t   t   t   t     )
        ( DIODE           iso             DIODE_iso                       t   t   t   t   t     )
        ( CAP             mark            CAP_mark                        t   t   t   t   t     )
        ( MOM             mark            MOM_mark                        t   t   t   t   t     )
        ( MOM             ter             MOM_ter                         t   t   t   t   t     )
        ( BJT             mark            BJT_mark                        t   t   t   t   t     )
        ( RFDUM           g2              designFlow118                   t   t   t   t   t     )
        ( RFDUM           mark            RFDUM_mark                      t   t   t   t   t     )
        ( INDUM           mark            INDUM_mark                      t   t   t   t   t     )
        ( EXCLU           mark            designFlow                      t   t   t   t   t     )
        ( NOBIAS          mark            NOBIAS                          t   t   t   t   t     )
        ( SGND            mark            designFlow6                     t   t   t   t   t     )
        ( DUMBM           mark            y0                              t   t   t   t   t     )
        ( DUMBP           mark            y1                              t   t   t   t   t     )
        ( DUMBA           mark            y2                              t   t   t   t   t     )
        ( NODMF           mark            y3                              t   t   t   t   t     )
        ( OPCBLK          mark            y4                              t   t   t   t   t     )
        ( VTSRAM          mark            y5                              t   t   t   t   t     )
        ( A1DUM           dumy            aabs_m1drawing                  t   t   t   t   t     )
        ( A2DUM           dumy            aabs_m2drawing                  t   t   t   t   t     )
        ( A3DUM           dumy            aabs_m3drawing                  t   t   t   t   t     )
        ( A4DUM           dumy            aabs_m4drawing                  t   t   t   t   t     )
        ( A5DUM           dumy            aabs_m5drawing                  t   t   t   t   t     )
        ( ATDUM           dumy            aabs_m6drawing                  t   t   t   t   t     )
        ( MTTDUM          dumy            aabs_m6drawing                  t   t   t   t   t     )
        ( TODUM           dumy            aabs_m7drawing                  t   t   t   t   t     )
        ( GTDUM           dumy            aabs_m8drawing                  t   t   t   t   t     )
        ( A1DUM           DB              A1DUM_DB                        t   t   t   t   t     )
        ( A2DUM           DB              A2DUM_DB                        t   t   t   t   t     )
        ( A3DUM           DB              A3DUM_DB                        t   t   t   t   t     )
        ( A4DUM           DB              A4DUM_DB                        t   t   t   t   t     )
        ( A5DUM           DB              A5DUM_DB                        t   t   t   t   t     )
        ( ATDUM           DB              ATDUM_DB                        t   t   t   t   t     )
        ( MTTDUM          DB              MTTDUM_DB                       t   t   t   t   t     )
        ( VTSRAM          g2              VTSRAM_g2                       t   t   t   t   t     )
        ( VTSRAM          g3              VTSRAM_g3                       t   t   t   t   t     )
        ( TB              net             tbnet                           t   t   t   t   t     )
        ( MCT             net             MCT_net                         t   t   t   t   t     )
        ( DN              net             dnnet                           t   t   t   t   t     )
        ( GT              label           met1Lbl                         t   t   t   t   t     )
        ( GT              pin             met1Pin                         t   t   t   t   t     )
        ( GT              boundary        met1Bnd                         t   t   t   t   t     )
        ( GT              net             met1                            t   t   t   t   t     )
        ( A1              label           met1Lbl                         t   t   t   t   t     )
        ( A1              pin             A1_pin                          t   t   t   t   t     )
        ( A1              boundary        aabs_m1boundary                 t   t   t   t   t     )
        ( A1              net             aabs_m1net                      t   t   t   t   t     )
        ( A2              label           met2Lbl                         t   t   t   t   t     )
        ( A2              pin             aabs_m2pin                      t   t   t   t   t     )
        ( A2              boundary        aabs_m2boundary                 t   t   t   t   t     )
        ( A2              net             aabs_m2net                      t   t   t   t   t     )
        ( A3              label           met3Lbl                         t   t   t   t   t     )
        ( A3              pin             aabs_m3pin                      t   t   t   t   t     )
        ( A3              boundary        aabs_m3boundary                 t   t   t   t   t     )
        ( A3              net             aabs_m3net                      t   t   t   t   t     )
        ( A4              label           met4Lbl                         t   t   t   t   t     )
        ( A4              pin             aabs_m4pin                      t   t   t   t   t     )
        ( A4              boundary        aabs_m4boundary                 t   t   t   t   t     )
        ( A4              net             aabs_m4net                      t   t   t   t   t     )
        ( A5              label           met5Lbl                         t   t   t   t   t     )
        ( A5              pin             aabs_m5pin                      t   t   t   t   t     )
        ( A5              boundary        aabs_m5boundary                 t   t   t   t   t     )
        ( A5              net             aabs_m5net                      t   t   t   t   t     )
        ( AT              label           met6Lbl                         t   t   t   t   t     )
        ( AT              pin             aabs_m6pin                      t   t   t   t   t     )
        ( AT              boundary        aabs_m6boundary                 t   t   t   t   t     )
        ( AT              net             aabs_m6net                      t   t   t   t   t     )
        ( MTT             label           met6Lbl                         t   t   t   t   t     )
        ( MTT             pin             aabs_m6pin                      t   t   t   t   t     )
        ( MTT             boundary        aabs_m6boundary                 t   t   t   t   t     )
        ( MTT             net             aabs_m6net                      t   t   t   t   t     )
        ( W1              net             aabs_vP1net                     t   t   t   t   t     )
        ( W1              pin             aabs_vP1pin                     t   t   t   t   t     )
        ( W1              boundary        aabs_vP1boundary                t   t   t   t   t     )
        ( W2              net             aabs_v12net                     t   t   t   t   t     )
        ( W2              pin             aabs_v12pin                     t   t   t   t   t     )
        ( W2              boundary        aabs_v12boundary                t   t   t   t   t     )
        ( W3              net             aabs_v23net                     t   t   t   t   t     )
        ( W3              pin             aabs_v23pin                     t   t   t   t   t     )
        ( W3              boundary        aabs_v23boundary                t   t   t   t   t     )
        ( W4              net             aabs_v34net                     t   t   t   t   t     )
        ( W4              pin             aabs_v34pin                     t   t   t   t   t     )
        ( W4              boundary        aabs_v34boundary                t   t   t   t   t     )
        ( W5              net             aabs_v45net                     t   t   t   t   t     )
        ( W5              pin             aabs_v45pin                     t   t   t   t   t     )
        ( W5              boundary        aabs_v45boundary                t   t   t   t   t     )
        ( WT              net             aabs_v56net                     t   t   t   t   t     )
        ( WT              pin             aabs_v56pin                     t   t   t   t   t     )
        ( WT              boundary        aabs_v56boundary                t   t   t   t   t     )
    ) ;techDisplays

    techLayerPurposePriorities(
;       ( LayerName       Purpose          )
;       ( ---------       -------          )
    
        ( text                 drawing          )
        ( prBoundary      drawing          )
      
    ) ;techLayerPurposePriorities
    techDisplays(
;       ( LayerName       Purpose         Packet                          Vis Sel Chg Drg Valid )
;       ( ---------       -------         ------                          --- --- --- --- ----- )
        ( text                 drawing         text                                           t   t   t   t   t     )
        ( prBoundary      drawing         aabs_prBoundarydrawing          t   t   t   t   t     )
       
    ) ;techDisplays
    techDerivedLayers(
;       ( DerivedName     Layer#          ( Composition )                  )
;       ( -----------     ------          ---------------                  )
        ( sn_ovlp_sp      1000            ( SN 'and SP )                   )
        ( techfile21596   1001            ( GT 'and W1 )                   )
        ( w1_err          1002            ( TO 'and techfile21596 )        )
        ( w1_to           1003            ( TO 'and W1 )                   )
    ) ;techDerivedLayers
 

) ;layerDefinitions


layerRules(

    functions(
;       ( layer           function        maskNumber       )
;       ( -----           --------        ----------       )
        ( TB              "nwell"         1                )
        ( TO              "diff"          2                )
        ( SN              "nplus"         3                )
        ( SP              "pplus"         4                )
        ( GT              "poly"          5                )
        ( W1              "cut"           6                )
        ( A1              "metal"         7                )
        ( W2              "cut"           12               )
        ( A2              "metal"         13               )
        ( W3              "cut"           14               )
        ( A3              "metal"         15               )
        ( W4              "cut"           16               )
        ( A4              "metal"         17               )
        ( W5              "cut"           18               )
        ( A5              "metal"         19               )
        ( WT              "cut"           20               )
        ( AT              "metal"         21               )
    ) ;functions

    routingDirections(
;       ( layer           direction        )
;       ( -----           ---------        )
        ( A1              "horizontal"     )
        ( A2              "vertical"       )
        ( A3              "horizontal"     )
        ( A4              "vertical"       )
        ( A5              "horizontal"     )
        ( AT              "vertical"       )
    ) ;routingDirections

) ;layerRules


viaDefs(

    standardViaDefs(
;       ( viaDefName      layer1      layer2      ( cutLayer    cutWidth    cutHeight   [resPerCut]  )
;           ( cutRows cutCols (cutSpace)       )
;           (layer1Enc)     (layer2Enc)     (layer1Offset)  (layer2Offset)  (origOffset)    
;         [ implant1    (implantEnc1)     [ implant2    (implantEnc2)     [ well/substrate  ]]]
;       )
;       ( ------------------------------------------------------------------------------------------ )
        ( NDIFF_M1        TO          A1          ( W1          0.186       0.186                    )
            ( 1       1       (0.238 0.238)    )
            (0.07 0.07)     (0.004 0.05)    (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
            SN          (0.152 0.152)   
        )

        ( PDIFF_M1        TO          A1          ( W1          0.186       0.186                    )
            ( 1       1       (0.238 0.238)    )
            (0.07 0.07)     (0.004 0.05)    (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
            SP          (0.152 0.152)   
        )

        ( POLY_M1         GT          A1          ( W1          0.186       0.186                    )
            ( 1       1       (0.238 0.238)    )
            (0.07 0.07)     (0.004 0.05)    (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
        )

        ( M1_M2           A1          A2          ( W2          0.22        0.22                     )
            ( 1       1       (0.22 0.22)      )
            (0 0.06)        (0 0.05)        (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
        )

        ( M2_M3           A2          A3          ( W3          0.22        0.22                     )
            ( 1       1       (0.22 0.22)      )
            (0 0.06)        (0 0.05)        (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
        )

        ( M3_M4           A3          A4          ( W4          0.22        0.22                     )
            ( 1       1       (0.22 0.22)      )
            (0 0.06)        (0 0.05)        (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
        )

        ( M4_M5           A4          A5          ( W5          0.22        0.22                     )
            ( 1       1       (0.22 0.22)      )
            (0 0.06)        (0 0.05)        (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
        )

        ( M5_MT           A5          AT          ( WT          0.238       0.238                    )
            ( 1       1       (0.238 0.238)    )
            (0 0.06)        (0.07 0.1)      (0.0 0.0)       (0.0 0.0)       (0.0 0.0)       
        )

    ) ;standardViaDefs

    customViaDefs(
;       ( viaDefName      libName     cellName    viewName    botLayer    topLayer    resPerCut    )
;       ( ----------      -------     --------    --------    --------    --------    ---------    )
        ( M1_M2_via       c1513       M1_M2       via         A1          A2          8            )
        ( M2_M3_via       c1513       M2_M3       via         A2          A3          8            )
        ( M3_M4_via       c1513       M3_M4       via         A3          A4          8            )
        ( M4_M5_via       c1513       M4_M5       via         A4          A5          8            )
        ( M5_MT_via       c1513       M5_MT       via         A5          AT          5            )
    ) ;customViaDefs

) ;viaDefs


constraintGroups(
;   ( group           override
;     -----           --------

    ( "foundry"

        spacings(
;           ( constraint                      layer1          layer2          value            )
;           ( ----------                      ------          ------          -----            )
            (minWidth                        TO                              0.186           
                'ref "TO.a")
            (minWidth                        GT                              0.18            
                'ref "GT.a")
            (minWidth                        A1                              0.194           
                'ref "A1.a")
            (minSpacing                      TO                              0.238           
                'ref "TO.c")
            (minSpacing                      GT                              0.212           
                'ref "GT.d")
            (minArea                         A1                              0.2             
                'ref "A1.h")
            (minArea                         TO                              0.2             
                'ref "TO.n")
            (minWidth                        A2                              0.238           
                'ref "An.a")
            (minArea                         A2                              0.2             
                'ref "An.h")
            (minWidth                        A3                              0.238           
                'ref "An.a")
            (minArea                         A3                              0.2             
                'ref "An.h")
            (minWidth                        A4                              0.238           
                'ref "An.a")
            (minArea                         A4                              0.2             
                'ref "An.h")
            (minWidth                        A5                              0.238           
                'ref "An.a")
            (minArea                         A5                              0.2             
                'ref "An.h")
            (minWidth                        AT                              0.42            
                'ref "AT.a")
            (minArea                         AT                              0.56            
                'ref "AT.e")
            (minWidth                        W1                              0.186           
                'ref "W1.a")
            (minSpacing                      W1                              0.212           
                'ref "W1.b")
            (minWidth                        W2                              0.22            
                'ref "Wn.a")
            (minSpacing                      W2                              0.22            
                'ref "Wn.b")
            (minWidth                        W3                              0.22            
                'ref "Wn.a")
            (minSpacing                      W3                              0.22            
                'ref "Wn.b")
            (minWidth                        W4                              0.22            
                'ref "Wn.a")
            (minSpacing                      W4                              0.22            
                'ref "Wn.b")
            (minWidth                        W5                              0.22            
                'ref "Wn.a")
            (minSpacing                      W5                              0.22            
                'ref "Wn.b")
            (minWidth                        WT                              0.238           
                'ref "WT.a")
            (minSpacing                      WT                              0.238           
                'ref "WT.b")
        ) ;spacings

        orderedSpacings(
;           ( constraint                      layer1          layer2          [layer3]        value            )
;           ( ----------                      ------          ------          --------        -----            )
            (minOppExtension                 TO              W1                              ( 0.07 0.07 )   
                'ref "W1.e")
            (minOppExtension                 GT              W1                              ( 0.07 0.07 )   
                'ref "W1.f")
            (minOppExtension                 A1              W1                              (0.004 0.05)    
                'ref "A1.c")
            (minOppExtension                 A1              W2                              (0 0.06)        
                'ref "Wn.c")
            (minOppExtension                 A2              W3                              (0 0.06)        
                'ref "Wn.c")
            (minOppExtension                 A3              W4                              (0 0.06)        
                'ref "Wn.c")
            (minOppExtension                 A4              W5                              (0 0.06)        
                'ref "Wn.c")
            (minOppExtension                 A5              WT                              (0 0.06)        
                'ref "WT.c")
            (minOppExtension                 A2              W2                              (0 0.05)        
                'ref "An.c")
            (minOppExtension                 A3              W3                              (0 0.05)        
                'ref "An.c")
            (minOppExtension                 A4              W4                              (0 0.05)        
                'ref "An.c")
            (minOppExtension                 A5              W5                              (0 0.05)        
                'ref "An.c")
            (minOppExtension                 AT              WT                              (0.07 0.1)      
                'ref "AT.c")
        ) ;orderedSpacings

        spacingTables(
;           ( constraint                      layer1          layer2          layer3          
;               ( (index1Definitions [index2Definitions]) [defaultValue] )
;               ( table ) )
;           ( ---------------------------------------------------------- )
            ( minSpacing                      A1                              
                ( ( "width" nil nil ) 0.194 )
                (
                    0 0.194
                    10 0.476
                )
            )
            ( minSpacing                      A2                              
                ( ( "width" nil nil ) 0.238 )
                (
                    0 0.238
                    10 0.476
                )
            )
            ( minSpacing                      A3                              
                ( ( "width" nil nil ) 0.238 )
                (
                    0 0.238
                    10 0.476
                )
            )
            ( minSpacing                      A4                              
                ( ( "width" nil nil ) 0.238 )
                (
                    0 0.238
                    10 0.476
                )
            )
            ( minSpacing                      A5                              
                ( ( "width" nil nil ) 0.238 )
                (
                    0 0.238
                    10 0.476
                )
            )
            ( minSpacing                      AT                              
                ( ( "width" nil nil ) 0.42 )
                (
                    0 0.42
                    10 0.51
                )
            )
        ) ;spacingTables

    ) ;foundry

    ( "virtuosoDefaultExtractorSetup"

        interconnect(
            (validLayers   (TB  TO  GT  W1  A1  W2  A2  W3  A3  W4 A4 W5 A5 WT  AT  ))

        ) ;interconnect

    ) ;virtuosoDefaultExtractorSetup

    ( "virtuosoDefaultSetup"

        interconnect(
            (validLayers   (GT  A1  A2  A3  A4  A5 AT))
            (validVias      (NDIFF_M1  PDIFF_M1  POLY_M1  M1_M2  M2_M3  M3_M4  M4_M5  M5_MT ))

        ) ;interconnect

    ) ;virtuosoDefaultSetup

    ( "VLMDefaultSetup"

        interconnect(
            (validVias     (POLY_M1  M1_M2  M2_M3  M3_M4  M4_M5 M5_MT ))

        ) ;interconnect

    ) ;VLMDefaultSetup

    ( "LEFDefaultRouteSpec"

        routingGrids(
            ( verticalPitch            	"A1"   0.388 )
            ( horizontalPitch            	"A1"   0.388 )
            ( verticalOffset             	"A1"   0.194 )
            ( horizontalOffset           	"A1"   0.194 )
            ( verticalPitch              	"A2"   0.476 )
            ( horizontalPitch            	"A2"   0.476 )
            ( verticalOffset             	"A2"   0.238 )
            ( horizontalOffset           	"A2"   0.238 )
            ( verticalPitch              	"A3"   0.476 )
            ( horizontalPitch            	"A3"   0.476 )
            ( verticalOffset             	"A3"   0.238 )
            ( horizontalOffset           	"A3"   0.238 )
            ( verticalPitch              	"A4"   0.476 )
            ( horizontalPitch            	"A4"   0.476 )
            ( verticalOffset             	"A4"   0.238 )
            ( horizontalOffset           	"A4"   0.238 )
            ( verticalPitch              	"A5"   0.476 )
            ( horizontalPitch            	"A5"   0.476 )
            ( verticalOffset             	"A5"   0.238 )
            ( horizontalOffset           	"A5"   0.238 )
            ( verticalPitch              	"AT"   0.84 )
            ( horizontalPitch            	"AT"   0.84 )
            ( verticalOffset             	"AT"   0.42 )
            ( horizontalOffset           	"AT"   0.42 )

        ) ;routingGrids

        interconnect(
            (validLayers   (A1  A2  A3  A4  A5 AT  ))
            (validVias      (M1_M2  M2_M3 M3_M4 M4_M5 M5_MT ))

        ) ;interconnect

    ) ;LEFDefaultRouteSpec

) ;constraintGroups


devices(

multipartPathTemplates(
; ( name [masterPath] [offsetSubpaths] [encSubPaths] [subRects] )
; 
;   masterPath:
;   (layer [width] [choppable] [endType] [beginExt] [endExt] [justify] [offset]
;   [connectivity])
; 
;   offsetSubpaths:
;   (layer [width] [choppable] [separation] [justification] [begOffset] [endOffset]
;   [connectivity])
; 
;   encSubPaths:
;   (layer [enclosure] [choppable] [separation] [begOffset] [endOffset]
;   [connectivity])
; 
;   subRects:
;   (layer [width] [length] [choppable] [separation] [justification] [space] [begOffset] [endOffset] [gap] 
;   [connectivity] [beginSegOffset] [endSegOffset])
; 
;   connectivity:
;   ([I/O type] [pin] [accDir] [dispPinName] [height] [ layer]
;    [layer] [justification] [font] [textOptions] [orientation]
;    [refHandle] [offset])
; 
; ( --------------------------------------------------------------------- )
  (PsubGuardRing 
    (("TO" "drawing")	0.326	t	truncate  	0.0)
    (
     (("A1" "drawing")	0.194	t	0.0	center    	0         	0         )
     (("SP" "drawing")	0.63	t	0       center    	0         	0         )
    )
    nil
    (
     (("W1" "drawing")	0.186	0.186	t	0.0	center	0.212	-0.1	-0.1	distribute	nil	0.0	0.0)
    )
  )
  (NwellGuardRing
    (("TO" "drawing")	0.326	t	truncate  	0.0)
    (
     (("A1" "drawing")	0.194	t	0.0	center    	0         	0         )
     (("SN" "drawing")	0.63	t	0       center    	0         	0         )
    )
    nil
    (
     (("W1" "drawing")	0.186	0.186	t	0.0	center	0.212	-0.1	-0.1	distribute	nil	0.0	0.0)
    )
  )
)  ;multipartPathTemplates


) ;devices


